Repository neo4j/docs-cypher, pull requests merged in 2023-10, with the labels that each got.

#754 Updates the return values to reflect what the product actually returns.
  modules/ROOT/pages/functions/mathematical-logarithmic.adoc
  modules/ROOT/pages/functions/mathematical-trigonometric.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, team-cypher-surface, dev

#756 Updates the return values to reflect what the product actually returns (#754)
  modules/ROOT/pages/functions/mathematical-logarithmic.adoc
  modules/ROOT/pages/functions/mathematical-trigonometric.adoc
Labels: cherry-picked, 5.x

#757 Updates the return values to reflect what the product actually returns. (#754)
  modules/ROOT/pages/functions/mathematical-logarithmic.adoc
  modules/ROOT/pages/functions/mathematical-trigonometric.adoc
Labels: 4.4, cherry-picked

#758 Add link to PDF
  modules/ROOT/pages/introduction/index.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#760 Add link to PDF (#758)
  modules/ROOT/pages/introduction/index.adoc
Labels: 4.4, cherry-picked

#759 Add link to PDF (#758)
  modules/ROOT/pages/introduction/index.adoc
Labels: cherry-picked, 5.x

#761 clarify about initial settings
  modules/ROOT/pages/administration/databases.adoc
Labels: cherry-pick-this-to-5.x, clustering, dev

#748 Add char_length and character_length functions
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/scalar.adoc
Labels: team-cypher-surface, dev, 5.13

#722 Update for vector search index in 5.13
  modules/ROOT/pages/indexes-for-vector-search.adoc
Labels: 5.13

#765 updated exact version
  antora.yml
Labels: 4.4, do not cherry-pick forward

#766 Remove Administration pages + Keyword Glossary page
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/administration/access-control/built-in-roles.adoc
  modules/ROOT/pages/administration/access-control/database-administration.adoc
  modules/ROOT/pages/administration/access-control/dbms-administration.adoc
  modules/ROOT/pages/administration/access-control/index.adoc
  modules/ROOT/pages/administration/access-control/limitations.adoc
  modules/ROOT/pages/administration/access-control/load-privileges.adoc
  modules/ROOT/pages/administration/access-control/manage-privileges.adoc
  modules/ROOT/pages/administration/access-control/manage-roles.adoc
  modules/ROOT/pages/administration/access-control/manage-users.adoc
  modules/ROOT/pages/administration/access-control/privileges-immutable.adoc
  modules/ROOT/pages/administration/access-control/privileges-reads.adoc
  modules/ROOT/pages/administration/access-control/privileges-writes.adoc
  modules/ROOT/pages/administration/aliases.adoc
  modules/ROOT/pages/administration/databases.adoc
  modules/ROOT/pages/administration/index.adoc
  modules/ROOT/pages/administration/servers.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/listing-functions.adoc
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/graph.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/introduction/cypher_neo4j.adoc
  modules/ROOT/pages/keyword-glossary.adoc
Labels: 5.13

#772 Fix CDC broken link
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-pick-this-to-5.x

#773 Fix CDC broken link (#772)
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-picked, 5.x
