Repository neo4j/docs-cypher, pull requests merged in 2023-09, with the labels that each got.

#678 Update CypherTypes in procedure/function descriptions
  modules/ROOT/pages/administration/access-control/manage-privileges.adoc
  modules/ROOT/pages/administration/access-control/manage-users.adoc
  modules/ROOT/pages/administration/databases.adoc
  modules/ROOT/pages/administration/servers.adoc
  modules/ROOT/pages/clauses/listing-functions.adoc
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/clauses/set.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/functions/aggregating.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/list.adoc
  modules/ROOT/pages/functions/load-csv.adoc
  modules/ROOT/pages/functions/mathematical-logarithmic.adoc
  modules/ROOT/pages/functions/mathematical-numeric.adoc
  modules/ROOT/pages/functions/mathematical-trigonometric.adoc
  modules/ROOT/pages/functions/predicate.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/functions/spatial.adoc
  modules/ROOT/pages/functions/string.adoc
  modules/ROOT/pages/functions/temporal/duration.adoc
  modules/ROOT/pages/functions/temporal/index.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/introduction/cypher_tutorial.adoc
  modules/ROOT/pages/keyword-glossary.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/values-and-types/casting-data.adoc
  modules/ROOT/pages/values-and-types/spatial.adoc
  modules/ROOT/pages/values-and-types/temporal.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-surface, dev

#713 Update CypherTypes in procedure/function descriptions (#678)
  modules/ROOT/pages/administration/access-control/manage-privileges.adoc
  modules/ROOT/pages/administration/access-control/manage-users.adoc
  modules/ROOT/pages/administration/databases.adoc
  modules/ROOT/pages/administration/servers.adoc
  modules/ROOT/pages/clauses/listing-functions.adoc
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/clauses/set.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/functions/aggregating.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/list.adoc
  modules/ROOT/pages/functions/load-csv.adoc
  modules/ROOT/pages/functions/mathematical-logarithmic.adoc
  modules/ROOT/pages/functions/mathematical-numeric.adoc
  modules/ROOT/pages/functions/mathematical-trigonometric.adoc
  modules/ROOT/pages/functions/predicate.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/functions/spatial.adoc
  modules/ROOT/pages/functions/string.adoc
  modules/ROOT/pages/functions/temporal/duration.adoc
  modules/ROOT/pages/functions/temporal/index.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/introduction/cypher_tutorial.adoc
  modules/ROOT/pages/keyword-glossary.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/values-and-types/casting-data.adoc
  modules/ROOT/pages/values-and-types/spatial.adoc
  modules/ROOT/pages/values-and-types/temporal.adoc
Labels: cherry-picked, 5.x

#712 Type constraint index tuning
  modules/ROOT/pages/constraints/index.adoc
  modules/ROOT/pages/query-tuning/indexes.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-planner, 5.11

#714 Type constraint index tuning (#712)
  modules/ROOT/pages/constraints/index.adoc
  modules/ROOT/pages/query-tuning/indexes.adoc
Labels: cherry-picked, 5.x

#670 Restructure the main part of create.adoc
  modules/ROOT/pages/clauses/create.adoc
  modules/ROOT/pages/clauses/set.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-planner

#715 Restructure the main part of create.adoc (#670)
  modules/ROOT/pages/clauses/create.adoc
  modules/ROOT/pages/clauses/set.adoc
Labels: cherry-picked, 5.x

#716 Add page aliases for 4.4 to 5
  modules/ROOT/pages/administration/databases.adoc
  modules/ROOT/pages/introduction/cypher_neo4j.adoc
  modules/ROOT/pages/patterns/index.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
Labels: cherry-pick-this-to-5.x, dev

#718 Add page aliases for 3.5 to 4.0
  modules/ROOT/pages/administration/constraints.adoc
  modules/ROOT/pages/administration/indexes-for-search-performance.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/introduction/quering-updating-administering.adoc
  modules/ROOT/pages/query-tuning/advanced-example.adoc
  modules/ROOT/pages/query-tuning/basic-example.adoc
Labels: 4.0

#719 Add page aliases for 4.2 to 4.3
  modules/ROOT/pages/access-control/built-in-roles.adoc
  modules/ROOT/pages/access-control/database-administration.adoc
  modules/ROOT/pages/access-control/dbms-administration.adoc
  modules/ROOT/pages/access-control/index.adoc
  modules/ROOT/pages/access-control/limitations.adoc
  modules/ROOT/pages/access-control/manage-privileges.adoc
  modules/ROOT/pages/access-control/manage-roles.adoc
  modules/ROOT/pages/access-control/manage-users.adoc
  modules/ROOT/pages/access-control/privileges-reads.adoc
  modules/ROOT/pages/access-control/privileges-writes.adoc
  modules/ROOT/pages/constraints/index.adoc
  modules/ROOT/pages/databases.adoc
  modules/ROOT/pages/indexes-for-full-text-search.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
Labels: 4.3

#724 Add page aliases for 4.4 to 5 (#716)
  modules/ROOT/pages/administration/databases.adoc
  modules/ROOT/pages/introduction/cypher_neo4j.adoc
  modules/ROOT/pages/patterns/index.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
Labels: cherry-picked, 5.x

#725 Publish 5.12 Cypher Manual (#694)
  antora.yml
Labels: cherry-picked, 5.x, 5.12

#717 documentation for db.nameFromElementId
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/functions/database.adoc
  modules/ROOT/pages/functions/index.adoc
Labels: cherry-pick-this-to-5.x, dev, 5.12, team-cypher-composite

#727 documentation for db.nameFromElementId (#717)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/functions/database.adoc
  modules/ROOT/pages/functions/index.adoc
Labels: cherry-picked, 5.12

#726 update Antora for 5.13
  antora.yml
Labels: 5.13

#728 Add db.namefromelementid function to additions/deprecations page
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-pick-this-to-5.x, 5.12

#729 Add missing release version labels to db functions
  modules/ROOT/pages/functions/database.adoc
  modules/ROOT/pages/functions/index.adoc
Labels: cherry-pick-this-to-5.x, 5.12

#730 Add db.namefromelementid function to additions/deprecations page (#728)
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-picked, 5.x, 5.12

#731 Add missing release version labels to db functions (#729)
  modules/ROOT/pages/functions/database.adoc
  modules/ROOT/pages/functions/index.adoc
Labels: cherry-picked, 5.x, 5.12

#687 Add docs for valueType function
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
Labels: team-cypher-surface, 5.13

#697 Restructuring Expressions
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/call_subquery_graph.svg
  modules/ROOT/images/case_graph.svg
  modules/ROOT/images/graph3.svg
  modules/ROOT/images/graph_call_subquery_clause.svg
  modules/ROOT/images/graph_expression_subqueries.svg
  modules/ROOT/images/graph_expression_type_predicate.svg
  modules/ROOT/images/subqueries_graph.svg
  modules/ROOT/images/type_predicate_expression_graph.svg
  modules/ROOT/pages/clauses/call-subquery.adoc
  modules/ROOT/pages/clauses/call.adoc
  modules/ROOT/pages/clauses/clause_composition.adoc
  modules/ROOT/pages/clauses/delete.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/predicate.adoc
  modules/ROOT/pages/introduction/cypher_neo4j.adoc
  modules/ROOT/pages/introduction/index.adoc
  modules/ROOT/pages/keyword-glossary.adoc
  modules/ROOT/pages/patterns/index.adoc
  modules/ROOT/pages/patterns/primer.adoc
  modules/ROOT/pages/patterns/reference.adoc
  modules/ROOT/pages/queries/basic.adoc
  modules/ROOT/pages/queries/case.adoc
  modules/ROOT/pages/queries/concepts.adoc
  modules/ROOT/pages/queries/expressions.adoc
  modules/ROOT/pages/queries/index.adoc
  modules/ROOT/pages/subqueries/call-subquery.adoc
  modules/ROOT/pages/subqueries/collect.adoc
  modules/ROOT/pages/subqueries/count.adoc
  modules/ROOT/pages/subqueries/existential.adoc
  modules/ROOT/pages/subqueries/index.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
  modules/ROOT/pages/syntax/expressions.adoc
  modules/ROOT/pages/syntax/index.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/syntax/parsing.adoc
  modules/ROOT/pages/values-and-types/index.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
  modules/ROOT/pages/values-and-types/type-predicate.adoc
  modules/ROOT/pages/values-and-types/working-with-null.adoc
Labels: cherry-pick-this-to-5.x, Cypher Manual Restructure

#736 Restructure Expressions
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/call_subquery_graph.svg
  modules/ROOT/images/case_graph.svg
  modules/ROOT/images/graph3.svg
  modules/ROOT/images/graph_call_subquery_clause.svg
  modules/ROOT/images/graph_expression_subqueries.svg
  modules/ROOT/images/graph_expression_type_predicate.svg
  modules/ROOT/images/subqueries_graph.svg
  modules/ROOT/images/type_predicate_expression_graph.svg
  modules/ROOT/pages/clauses/call-subquery.adoc
  modules/ROOT/pages/clauses/call.adoc
  modules/ROOT/pages/clauses/clause_composition.adoc
  modules/ROOT/pages/clauses/delete.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/predicate.adoc
  modules/ROOT/pages/introduction/cypher_neo4j.adoc
  modules/ROOT/pages/introduction/index.adoc
  modules/ROOT/pages/keyword-glossary.adoc
  modules/ROOT/pages/patterns/index.adoc
  modules/ROOT/pages/patterns/primer.adoc
  modules/ROOT/pages/patterns/reference.adoc
  modules/ROOT/pages/queries/basic.adoc
  modules/ROOT/pages/queries/case.adoc
  modules/ROOT/pages/queries/concepts.adoc
  modules/ROOT/pages/queries/expressions.adoc
  modules/ROOT/pages/queries/index.adoc
  modules/ROOT/pages/subqueries/call-subquery.adoc
  modules/ROOT/pages/subqueries/collect.adoc
  modules/ROOT/pages/subqueries/count.adoc
  modules/ROOT/pages/subqueries/existential.adoc
  modules/ROOT/pages/subqueries/index.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
  modules/ROOT/pages/syntax/expressions.adoc
  modules/ROOT/pages/syntax/index.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/syntax/parsing.adoc
  modules/ROOT/pages/values-and-types/index.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
  modules/ROOT/pages/values-and-types/type-predicate.adoc
  modules/ROOT/pages/values-and-types/working-with-null.adoc
Labels: cherry-picked, 5.x

#676 Update CypherTypes in procedure/function signatures
  modules/ROOT/pages/administration/databases.adoc
  modules/ROOT/pages/clauses/call.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/execution-plans/operators.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/indexes-for-vector-search.adoc
Labels: team-cypher-surface, dev, 5.13

#733 Re-document the split of EXECUTE and EXECUTE BOOSTED privileges
  modules/ROOT/pages/administration/access-control/dbms-administration.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations, dev

#738 Re-document the split of EXECUTE and EXECUTE BOOSTED privileges (#733)
  modules/ROOT/pages/administration/access-control/dbms-administration.adoc
Labels: cherry-picked, 5.x

#734 CDC documentation
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-operations, 5.13

#735 Alter database options
  modules/ROOT/pages/administration/databases.adoc
Labels: team-cypher-operations, 5.13

#732 Fix operator-summary.adoc
  modules/ROOT/pages/execution-plans/operator-summary.adoc
Labels: cherry-pick-this-to-5.x

#742 Fix operator-summary.adoc (#732)
  modules/ROOT/pages/execution-plans/operator-summary.adoc
Labels: cherry-picked, 5.x

#743 Small fix to core concepts page
  modules/ROOT/pages/queries/concepts.adoc
Labels: cherry-pick-this-to-5.x

#744 Small fix to core concepts page
  modules/ROOT/pages/queries/concepts.adoc
Labels: cherry-picked, 5.x

#746 Fix typo on CALL subquery page
  modules/ROOT/pages/subqueries/call-subquery.adoc
Labels: cherry-pick-this-to-5.x

#747 Fix typo on CALL subquery page (#746)
  modules/ROOT/pages/subqueries/call-subquery.adoc
Labels: cherry-picked, 5.x

#749 Small fixes
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
Labels: team-cypher-surface, dev, 5.13

#750 Add information about aggregations on zero rows
  modules/ROOT/pages/functions/aggregating.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#751 Add information about aggregations on zero rows (#750)
  modules/ROOT/pages/functions/aggregating.adoc
Labels: cherry-picked, 5.x

#752 Add graph.byElementId function
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/graph.adoc
  modules/ROOT/pages/functions/index.adoc
Labels: 5.13, team-cypher-composite
