Repository neo4j/docs-cypher, pull requests merged in 2023-08, with the labels that each got.

#671 New UI bundle url
  preview.yml
  publish.yml
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#674 New ui-bundle url
  preview.yml
Labels: 4.3, cherry-pick-this-to-4.2, cherry-pick-this-to-4.1

#672 New UI bundle url (#671)
  preview.yml
  publish.yml
Labels: cherry-picked, 5.x

#673 New UI bundle url (#671)
  preview.yml
  publish.yml
Labels: 4.4, cherry-picked

#679 New ui-bundle url
  preview.yml
  publish.yml
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, dev

#669 Type Predicate Expressions iteration 3
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/syntax/expressions.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
Labels: team-cypher-surface, 5.11

#681 Update GHA
  .github/workflows/docs-deploy-surge.yml
  .github/workflows/docs-pr.yml
  .github/workflows/docs-teardown.yml
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, dev

#667 Update `ProjectEndpoints` operator for 5.11
  modules/ROOT/pages/execution-plans/operators.adoc
Labels: 5.11

#675 UNION combines `any` queries
  modules/ROOT/pages/clauses/union.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-dev

#683 UNION combines `any` queries (#675)
  modules/ROOT/pages/clauses/union.adoc
Labels: cherry-picked, dev

#684 UNION combines `any` queries (#675)
  modules/ROOT/pages/clauses/union.adoc
Labels: 4.4, cherry-picked

#677 Add Closed Dynamic Union types to type constraints
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-operations, dev, 5.11

#680 Adding starting and stopping database state
  modules/ROOT/pages/administration/databases.adoc
Labels: clustering, 5.11

#686 Use "aggregating functions" consistently
  modules/ROOT/pages/functions/aggregating.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#689 Use "aggregating functions" consistently (#686)
  modules/ROOT/pages/functions/aggregating.adoc
Labels: cherry-picked, 5.x

#691 Add additional property type example to SHOW CONSTRAINTS
  modules/ROOT/pages/constraints/examples.adoc
Labels: team-cypher-operations, dev, 5.11

#692 Add note that ALTER CURRENT USER SET PASSWORD command auto-commits
  modules/ROOT/pages/administration/access-control/manage-users.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: 5.11

#690 Document vector indexes
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/cosine_similarity_equation.svg
  modules/ROOT/images/cosine_similarity_equation.tex
  modules/ROOT/images/euclidean_similarity_equation.svg
  modules/ROOT/images/euclidean_similarity_equation.tex
  modules/ROOT/images/l2.svg
  modules/ROOT/images/l2.tex
  modules/ROOT/images/l2norm_is_1.svg
  modules/ROOT/images/l2norm_is_1.tex
  modules/ROOT/pages/indexes-for-vector-search.adoc
Labels: 5.11

#695 Editorial clean up of new vector index page
  modules/ROOT/pages/indexes-for-vector-search.adoc
Labels: cherry-pick-this-to-5.x, 5.11

#696 Editorial clean up of new vector index page (#695)
  modules/ROOT/pages/indexes-for-vector-search.adoc
Labels: cherry-picked, 5.x

#698 Remove usage of "version" or "v" before the version number
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/syntax/expressions.adoc
  modules/ROOT/pages/syntax/parameters.adoc
Labels: cherry-pick-this-to-5.x

#702 Update vector index issues (#700)
  modules/ROOT/pages/indexes-for-vector-search.adoc
Labels: cherry-picked, 5.x, 5.11

#701 Remove link to removed `id` examples
  modules/ROOT/pages/functions/scalar.adoc
Labels: cherry-pick-this-to-5.x

#703 Remove link to removed `id` examples (#701)
  modules/ROOT/pages/functions/scalar.adoc
Labels: cherry-picked, 5.x

#705 update vector index known issue fixes
  modules/ROOT/pages/indexes-for-vector-search.adoc
Labels: cherry-pick-this-to-5.x, 5.11

#707 Corrected r.since to r.lastMetIn (#706)
  modules/ROOT/pages/query-tuning/indexes.adoc
Labels: cherry-picked, dev

#708 update vector index known issue fixes (#705)
  modules/ROOT/pages/indexes-for-vector-search.adoc
Labels: cherry-picked, 5.x

#709 Corrected r.since to r.lastMetIn (#706)
  modules/ROOT/pages/query-tuning/indexes.adoc
Labels: 4.4, cherry-picked
