Repository neo4j/docs-cypher, pull requests merged in 2023-06, with the labels that each got.

#587 Update clauses page (#586)
  modules/ROOT/pages/clauses/index.adoc
Labels: cherry-picked, 5.x

#598 Add example (set property to relationship) to SET page
  modules/ROOT/pages/clauses/set.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#599 Add example (set property to relationship) to SET page (#598)
  modules/ROOT/pages/clauses/set.adoc
Labels: cherry-picked, 5.x

#600 Add example (set property to relationship) to SET page (#598)
  modules/ROOT/pages/clauses/set.adoc
Labels: 4.4, cherry-picked

#589 Add link to notification docs in privilege docs
  modules/ROOT/pages/administration/access-control/database-administration.adoc
  modules/ROOT/pages/administration/access-control/manage-privileges.adoc
  modules/ROOT/pages/administration/access-control/manage-roles.adoc
Labels: team-cypher-operations, DO NOT MERGE, 5.9

#603 Composite databases will not appear in requestedHosting (#602)
  modules/ROOT/pages/administration/servers.adoc
Labels: cherry-picked, 5.x

#605 Add missing docs for COLLECT
  modules/ROOT/pages/keyword-glossary.adoc
  modules/ROOT/pages/syntax/index.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-surface, 5.x

#604 fixing typo
  modules/ROOT/pages/clauses/skip.adoc
Labels: cherry-pick-this-to-dev, 5.x, cherry-pick-this-to-4.1

#608 fixing typo (#604)
  modules/ROOT/pages/clauses/skip.adoc
Labels: cherry-picked, dev

#609 fixing typo (#604)
  modules/ROOT/pages/clauses/skip.adoc
Labels: 4.4, cherry-picked

#612 Fixing typo #604
  modules/ROOT/pages/clauses/skip.adoc
Labels: cherry-picked, 4.1

#585 Fix npm audit warnings
  README.adoc
  package-lock.json
  package.json
Labels: dev

#489 New Patterns chapter
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/path_pattern_example_graph.svg
  modules/ROOT/images/path_pattern_motif.svg
  modules/ROOT/images/path_pattern_solutions.svg
  modules/ROOT/images/patterns_equijoin_reference.svg
  modules/ROOT/images/patterns_equijoins.svg
  modules/ROOT/images/patterns_equijoins_motif.svg
  modules/ROOT/images/patterns_equijoins_motif2.svg
  modules/ROOT/images/patterns_equijoins_motif3.svg
  modules/ROOT/images/patterns_equijoins_solution.svg
  modules/ROOT/images/patterns_equijoins_solution2.svg
  modules/ROOT/images/patterns_graph_pattern_reference.svg
  modules/ROOT/images/patterns_graph_patterns_graph1.svg
  modules/ROOT/images/patterns_graph_patterns_graph2.svg
  modules/ROOT/images/patterns_group_variables_graph.svg
  modules/ROOT/images/patterns_group_variables_graph2.svg
  modules/ROOT/images/patterns_group_variables_graph3.svg
  modules/ROOT/images/patterns_node_pattern_pairs.svg
  modules/ROOT/images/patterns_primer.svg
  modules/ROOT/images/patterns_qpp_calling_points.svg
  modules/ROOT/images/patterns_qpp_illustration.svg
  modules/ROOT/images/patterns_qpp_motif1.svg
  modules/ROOT/images/patterns_qpp_motif2.svg
  modules/ROOT/images/patterns_qpp_query_breakdown.svg
  modules/ROOT/images/patterns_qpp_reference.svg
  modules/ROOT/images/patterns_qpp_reference_example.svg
  modules/ROOT/images/patterns_qpp_solutions.svg
  modules/ROOT/images/patterns_shortestpath.svg
  modules/ROOT/images/patterns_shortestpath_graph.svg
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/patterns/concepts.adoc
  modules/ROOT/pages/patterns/index.adoc
  modules/ROOT/pages/patterns/primer.adoc
  modules/ROOT/pages/patterns/reference.adoc
Labels: Cypher Manual Restructure, 5.9

#594 Add `isDeprecated` to show commands
  modules/ROOT/pages/clauses/listing-functions.adoc
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-operations, dev, 5.9

#578 Add `Repeat(Trail)` to operator list.
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/execution-plans/operator-summary.adoc
  modules/ROOT/pages/execution-plans/operators.adoc
Labels: team-cypher-planner, 5.9

#597 Add property type constraints
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/constraints/index.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/execution-plans/operators.adoc
  modules/ROOT/pages/introduction/cypher_neo4j.adoc
  modules/ROOT/pages/introduction/neo4j-databases-graphs.adoc
  modules/ROOT/pages/keyword-glossary.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
Labels: team-cypher-operations, Dependencies w. other PR, dev, 5.9

#618 Update antora for 5.10
  antora.yml
Labels: 5.10

#616 Update tutorial
  modules/ROOT/pages/introduction/cypher_tutorial.adoc
Labels: cherry-pick-this-to-5.x, 5.9

#620 Update tutorial (#616)
  modules/ROOT/pages/introduction/cypher_tutorial.adoc
Labels: cherry-picked, 5.x

#593 Add documentation around SHOW SUPPORTED PRIVILEGES
  modules/ROOT/pages/administration/access-control/manage-privileges.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/keyword-glossary.adoc
Labels: cherry-pick-this-to-5.x, new, team-cypher-operations, 5.9

#621 Add documentation around SHOW SUPPORTED PRIVILEGES (#593)
  modules/ROOT/pages/administration/access-control/manage-privileges.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/keyword-glossary.adoc
Labels: cherry-picked, 5.x

#614 Document type predicate expression
  modules/ROOT/images/graph_expression_type_predicate.svg
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/keyword-glossary.adoc
  modules/ROOT/pages/syntax/expressions.adoc
  modules/ROOT/pages/syntax/index.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
  modules/ROOT/pages/values-and-types/working-with-null.adoc
Labels: new, team-cypher-operations, team-cypher-surface, 5.9

#622 Document type predicate expression (#614)
  modules/ROOT/images/graph_expression_type_predicate.svg
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/keyword-glossary.adoc
  modules/ROOT/pages/syntax/expressions.adoc
  modules/ROOT/pages/syntax/index.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
  modules/ROOT/pages/values-and-types/working-with-null.adoc
Labels: cherry-picked, 5.x

#619 Update leftover review comments from adding property type constraints
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/keyword-glossary.adoc
Labels: team-cypher-operations, dev

#624 Update leftover review comments from adding property type constraints
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/keyword-glossary.adoc
Labels: cherry-picked, 5.x

#623 Fix formatting on constraints main page
  modules/ROOT/pages/constraints/index.adoc
Labels: bug, cherry-pick-this-to-5.x

#625 Fix formatting on constraints main page (#623)
  modules/ROOT/pages/constraints/index.adoc
Labels: cherry-picked, 5.x

#588 Documentation updates for clarifying what is allowed in LIMIT & Co
  modules/ROOT/pages/clauses/call-subquery.adoc
  modules/ROOT/pages/clauses/limit.adoc
  modules/ROOT/pages/clauses/skip.adoc
Labels: team-cypher-planner, dev

#626 Documentation updates for clarifying what is allowed in LIMIT & Co
  modules/ROOT/pages/clauses/call-subquery.adoc
  modules/ROOT/pages/clauses/limit.adoc
  modules/ROOT/pages/clauses/skip.adoc
Labels: cherry-picked, 5.x

#607 Deprecate self-references in CREATE clauses
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-planner, 5.9

#627 Deprecate self-references in CREATE clauses (#607)
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-picked, 5.x

#628 Remove old, unused intro pages
  modules/ROOT/pages/clauses/call-subquery.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/introduction/neo4j-databases-graphs.adoc
  modules/ROOT/pages/introduction/querying-updating-administering.adoc
  modules/ROOT/pages/introduction/transactions.adoc
  modules/ROOT/pages/introduction/uniqueness.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#630 fix show settings table
  modules/ROOT/pages/clauses/listing-settings.adoc
Labels: 5.10

#629 Remove old, unused intro pages (#628)
  modules/ROOT/pages/clauses/call-subquery.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/introduction/neo4j-databases-graphs.adoc
  modules/ROOT/pages/introduction/querying-updating-administering.adoc
  modules/ROOT/pages/introduction/transactions.adoc
  modules/ROOT/pages/introduction/uniqueness.adoc
Labels: cherry-picked, 5.x

#631 Add example of list syntax to server management commands
  modules/ROOT/pages/administration/servers.adoc
Labels: cherry-pick-this-to-5.x

#632 Add example of list syntax to server management commands
  modules/ROOT/pages/administration/servers.adoc
Labels: cherry-picked, 5.x

#635 Add info about count store
  modules/ROOT/pages/functions/aggregating.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#636 Add info about count store (#635)
  modules/ROOT/pages/functions/aggregating.adoc
Labels: cherry-picked, 5.x

#637 Add info about count store (#635)
  modules/ROOT/pages/functions/aggregating.adoc
Labels: 4.4, cherry-picked

#639 Fix introduction tutorial table
  modules/ROOT/pages/introduction/cypher_tutorial.adoc
Labels: cherry-pick-this-to-5.x

#640 Fix introduction tutorial table (#639)
  modules/ROOT/pages/introduction/cypher_tutorial.adoc
Labels: cherry-picked, 5.x

#641 Add example query for accessing map members
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/values-and-types/maps.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#643 Add example query for accessing map members (#641)
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/values-and-types/maps.adoc
Labels: 4.4, cherry-picked
