Repository neo4j/docs-cypher, pull requests merged in 2023-03, with the labels that each got.

#491 Add a PDF-specific title
  modules/ROOT/pages/introduction/index.adoc
Labels: cherry-pick-this-to-5.x, dev

#492 Update textual representation of path results
  modules/ROOT/pages/clauses/create.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/return.adoc
  modules/ROOT/pages/functions/list.adoc
  modules/ROOT/pages/functions/predicate.adoc
Labels: cherry-pick-this-to-5.x, 5.6

#493 Update textual representation of path results
  modules/ROOT/pages/clauses/create.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/return.adoc
  modules/ROOT/pages/functions/list.adoc
  modules/ROOT/pages/functions/predicate.adoc
Labels: cherry-picked, 5.x
