Repository neo4j/docs-cypher, pull requests merged in 2023-05, with the labels that each got.

#528 Add cheat sheet link to Aura intro page
  modules/ROOT/pages/introduction/cypher_aura.adoc
Labels: cherry-pick-this-to-5.x, Aura

#529 Add cheat sheet link to Aura intro page (#528)
  modules/ROOT/pages/introduction/cypher_aura.adoc
Labels: cherry-picked, 5.x, Aura

#526 Add 5.7 CALL IN TXs features to additions page
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-pick-this-to-5.x

#530 Add 5.7 CALL IN TXs features to additions page (#526)
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-picked, 5.x

#533 Small editorial change to introduction
  modules/ROOT/pages/introduction/cypher_neo4j.adoc
Labels: cherry-pick-this-to-5.x

#534 Small editorial change to introduction (#533)
  modules/ROOT/pages/introduction/cypher_neo4j.adoc
Labels: cherry-picked, 5.x

#532 New Introduction to 4.4
  antora.yml
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/introduction_example1.svg
  modules/ROOT/images/introduction_example2.svg
  modules/ROOT/images/introduction_schema.svg
  modules/ROOT/pages/administration/access-control/dbms-administration.adoc
  modules/ROOT/pages/clauses/call-subquery.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/introduction/cypher_aura.adoc
  modules/ROOT/pages/introduction/cypher_neo4j.adoc
  modules/ROOT/pages/introduction/cypher_overview.adoc
  modules/ROOT/pages/introduction/cypher_tutorial.adoc
  modules/ROOT/pages/introduction/index.adoc
  modules/ROOT/pages/introduction/neo4j-databases-graphs.adoc
  modules/ROOT/pages/introduction/quering-updating-administering.adoc
  preview.yml
  publish.yml
Labels: 4.4, cherry-picked

#516 New values and types chapter
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/graph5.svg
  modules/ROOT/images/graph6.svg
  modules/ROOT/images/values_and_types_converting_data_graph.svg
  modules/ROOT/images/values_and_types_lists_graph.svg
  modules/ROOT/images/values_and_types_maps_graph.svg
  modules/ROOT/pages/clauses/order-by.adoc
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/aggregating.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/list.adoc
  modules/ROOT/pages/functions/temporal/duration.adoc
  modules/ROOT/pages/functions/temporal/index.adoc
  modules/ROOT/pages/syntax/index.adoc
  modules/ROOT/pages/syntax/lists.adoc
  modules/ROOT/pages/syntax/maps.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/syntax/spatial.adoc
  modules/ROOT/pages/values-and-types/casting-data.adoc
  modules/ROOT/pages/values-and-types/index.adoc
  modules/ROOT/pages/values-and-types/lists.adoc
  modules/ROOT/pages/values-and-types/maps.adoc
  modules/ROOT/pages/values-and-types/property-structural-composite.adoc
  modules/ROOT/pages/values-and-types/spatial.adoc
  modules/ROOT/pages/values-and-types/temporal.adoc
  modules/ROOT/pages/values-and-types/working-with-null.adoc
Labels: Cypher Manual Restructure

#537 Fix Error Message display in new Values and Types chapter
  modules/ROOT/pages/values-and-types/casting-data.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#539 Add documentation license and remove reference to beginners in introduction
  modules/ROOT/pages/introduction/index.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#540 Add documentation license and remove reference to beginners in introduction
  modules/ROOT/pages/introduction/index.adoc
Labels: cherry-picked, 5.x

#541 Add documentation license and remove reference to beginners in introduction
  modules/ROOT/pages/introduction/index.adoc
Labels: 4.4, cherry-picked

#545 fix images on dbms administration page (#544)
  modules/ROOT/images/privileges_grant_and_deny_syntax_dbms_privileges.svg
  modules/ROOT/images/privileges_hierarchy_dbms.svg
Labels: cherry-picked, 5.x

#546 Add Not available on Aura role to SHOW SETTINGS page
  modules/ROOT/pages/clauses/listing-settings.adoc
Labels: cherry-pick-this-to-5.x, Aura

#547 Add Not available on Aura role to SHOW SETTINGS page (#546)
  modules/ROOT/pages/clauses/listing-settings.adoc
Labels: cherry-picked, Aura

#548 Remove reference to `dbms.cluster.overview`
  modules/ROOT/pages/administration/databases.adoc
Labels: cherry-pick-this-to-5.x, 5.x

#550 Add minor version release information on new features introduced between 5.1 and 5.8
  modules/ROOT/pages/administration/access-control/dbms-administration.adoc
  modules/ROOT/pages/administration/databases.adoc
  modules/ROOT/pages/administration/servers.adoc
  modules/ROOT/pages/clauses/call-subquery.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/constraints/index.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/execution-plans/operators.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/syntax/expressions.adoc
Labels: 5.8

#553 update all links to configs
  modules/ROOT/pages/administration/aliases.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/execution-plans/shortestpath-planning.adoc
  modules/ROOT/pages/query-caches/index.adoc
  modules/ROOT/pages/query-caches/unified-query-caches.adoc
  modules/ROOT/pages/query-tuning/advanced-example.adoc
  modules/ROOT/pages/query-tuning/basic-example.adoc
  modules/ROOT/pages/query-tuning/query-options.adoc
  modules/ROOT/pages/values-and-types/temporal.adoc
Labels: cherry-picked, 5.x

#543 Add graph.propertiesByName query example that selects subset of graphs
  modules/ROOT/pages/functions/graph.adoc
Labels: cherry-pick-this-to-5.x, 5.2

#555 Add graph.propertiesByName query example that selects subset of graphs
  modules/ROOT/pages/functions/graph.adoc
Labels: cherry-picked

#554 Fix misaligned entries in the TOC
  modules/ROOT/content-nav.adoc
Labels: bug, cherry-pick-this-to-5.x

#556 Fix misaligned entries in the TOC (#554)
  modules/ROOT/content-nav.adoc
Labels: cherry-picked

#559 Add 5.8 documentation for publication
  antora.yml
  modules/ROOT/pages/administration/access-control/dbms-administration.adoc
  modules/ROOT/pages/administration/databases.adoc
  modules/ROOT/pages/administration/servers.adoc
  modules/ROOT/pages/clauses/call-subquery.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/constraints/index.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/execution-plans/operator-summary.adoc
  modules/ROOT/pages/execution-plans/operators.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/syntax/expressions.adoc
Labels: 5.8

#562 document allowed whitespace characters (#531)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/syntax/index.adoc
  modules/ROOT/pages/syntax/naming.adoc
  modules/ROOT/pages/syntax/parsing.adoc
Labels: cherry-picked

#561 Add NODES 23 ad
  preview.yml
  publish.yml
Labels: 5.x

#564 5.8 dev reconciliation
  README.adoc
  modules/ROOT/pages/administration/access-control/built-in-roles.adoc
  modules/ROOT/pages/administration/access-control/manage-users.adoc
  modules/ROOT/pages/administration/aliases.adoc
  modules/ROOT/pages/administration/databases.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/functions/list.adoc
  modules/ROOT/pages/functions/temporal/index.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/introduction/cypher_overview.adoc
  modules/ROOT/pages/styleguide.adoc
Labels: 5.x

#566 Creating a database without specifying topology (#565)
  modules/ROOT/pages/administration/databases.adoc
Labels: cherry-picked, 5.x

#567 Remove 4.2 from Query Option table
  modules/ROOT/pages/query-tuning/query-options.adoc
Labels: 4.4

#570 Fix failing query plans
  modules/ROOT/pages/execution-plans/operators.adoc
Labels: 5.9

#557 Clarify composite database alias syntax
  modules/ROOT/pages/administration/aliases.adoc
Labels: cherry-pick-this-to-dev

#576 Clarify composite database alias syntax (#557)
  modules/ROOT/pages/administration/aliases.adoc
Labels: cherry-picked, dev

#577 Add operator NodeByElementIdSeek
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/execution-plans/operator-summary.adoc
  modules/ROOT/pages/execution-plans/operators.adoc
Labels: cherry-pick-this-to-5.x

#579 Add operator NodeByElementIdSeek (#577)
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/execution-plans/operator-summary.adoc
  modules/ROOT/pages/execution-plans/operators.adoc
Labels: cherry-picked, 5.x

#581 Remove duplicate notes on Expressions page
  modules/ROOT/pages/syntax/expressions.adoc
Labels: cherry-pick-this-to-5.x

#582 Remove duplicate notes on Expressions page (#581)
  modules/ROOT/pages/syntax/expressions.adoc
Labels: cherry-picked, 5.x
