Repository neo4j/docs-cypher, pull requests merged in 2023-12, with the labels that each got.

#800 Add `CREATE VECTOR INDEX` command for node vector indexes
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/indexes-for-vector-search.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: team-cypher-operations, 5.15

#808 Publish 5.15
  antora.yml
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/aggregating.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/indexes-for-vector-search.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning/indexes.adoc
  modules/ROOT/pages/syntax/naming.adoc
Labels: cherry-picked, 5.x, 5.15

#809 Update antora for 5.16
  antora.yml
Labels: 5.16

#811 remove connections ad
  publish.yml
Labels: 5.x, do not cherry-pick forward

#807 Add new `LOAD ON CIDR` privilege version to additions chapter
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-operations, 5.16

#810 Allow parameters for index and constraint names in create and drop commands
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/indexes-for-full-text-search.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/indexes-for-vector-search.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: team-cypher-operations, 5.16

#806 Add more details as to why a user would want to use nullIf
  modules/ROOT/pages/functions/scalar.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-surface

#818 Add more details as to why a user would want to use nullIf (#806)
  modules/ROOT/pages/functions/scalar.adoc
Labels: cherry-picked, 5.x

#805 Add known vector index issue where queries could be incorrectly rejected
  modules/ROOT/pages/indexes-for-vector-search.adoc
Labels: cherry-pick-this-to-5.x, 5.14

#821 Add known vector index issue where queries could be incorrectly rejected (#805)
  modules/ROOT/pages/indexes-for-vector-search.adoc
Labels: cherry-picked, 5.x, 5.14

#823 update version to 4.4.29
  antora.yml
Labels: 4.4
