Repository neo4j/docs-cypher, pull requests merged in 2023-04, with the labels that each got.

#494 New Administration chapter
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/administration/access-control/built-in-roles.adoc
  modules/ROOT/pages/administration/access-control/database-administration.adoc
  modules/ROOT/pages/administration/access-control/dbms-administration.adoc
  modules/ROOT/pages/administration/access-control/index.adoc
  modules/ROOT/pages/administration/access-control/limitations.adoc
  modules/ROOT/pages/administration/access-control/manage-privileges.adoc
  modules/ROOT/pages/administration/access-control/manage-roles.adoc
  modules/ROOT/pages/administration/access-control/manage-users.adoc
  modules/ROOT/pages/administration/access-control/privileges-immutable.adoc
  modules/ROOT/pages/administration/access-control/privileges-reads.adoc
  modules/ROOT/pages/administration/access-control/privileges-writes.adoc
  modules/ROOT/pages/administration/aliases.adoc
  modules/ROOT/pages/administration/databases.adoc
  modules/ROOT/pages/administration/index.adoc
  modules/ROOT/pages/administration/servers.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/listing-functions.adoc
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/indexes-for-full-text-search.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/introduction/cypher_neo4j.adoc
  modules/ROOT/pages/introduction/neo4j-databases-graphs.adoc
  modules/ROOT/pages/keyword-glossary.adoc
Labels: cherry-pick-this-to-5.x, Cypher Manual Restructure

#497 Fix SHOW SETTINGS result table with updated list of procedures
  modules/ROOT/pages/clauses/listing-settings.adoc
Labels: 5.7

#504 New Administration chapter
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/administration/access-control/built-in-roles.adoc
  modules/ROOT/pages/administration/access-control/database-administration.adoc
  modules/ROOT/pages/administration/access-control/dbms-administration.adoc
  modules/ROOT/pages/administration/access-control/index.adoc
  modules/ROOT/pages/administration/access-control/limitations.adoc
  modules/ROOT/pages/administration/access-control/manage-privileges.adoc
  modules/ROOT/pages/administration/access-control/manage-roles.adoc
  modules/ROOT/pages/administration/access-control/manage-users.adoc
  modules/ROOT/pages/administration/access-control/privileges-immutable.adoc
  modules/ROOT/pages/administration/access-control/privileges-reads.adoc
  modules/ROOT/pages/administration/access-control/privileges-writes.adoc
  modules/ROOT/pages/administration/aliases.adoc
  modules/ROOT/pages/administration/databases.adoc
  modules/ROOT/pages/administration/index.adoc
  modules/ROOT/pages/administration/servers.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/listing-functions.adoc
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/indexes-for-full-text-search.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/introduction/cypher_neo4j.adoc
  modules/ROOT/pages/introduction/neo4j-databases-graphs.adoc
  modules/ROOT/pages/keyword-glossary.adoc
Labels: cherry-picked, 5.x

#505 New Administration chapter
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/administration/access-control/built-in-roles.adoc
  modules/ROOT/pages/administration/access-control/database-administration.adoc
  modules/ROOT/pages/administration/access-control/dbms-administration.adoc
  modules/ROOT/pages/administration/access-control/index.adoc
  modules/ROOT/pages/administration/access-control/limitations.adoc
  modules/ROOT/pages/administration/access-control/manage-privileges.adoc
  modules/ROOT/pages/administration/access-control/manage-roles.adoc
  modules/ROOT/pages/administration/access-control/manage-users.adoc
  modules/ROOT/pages/administration/access-control/privileges-reads.adoc
  modules/ROOT/pages/administration/access-control/privileges-writes.adoc
  modules/ROOT/pages/administration/aliases.adoc
  modules/ROOT/pages/administration/databases.adoc
  modules/ROOT/pages/administration/index.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/listing-functions.adoc
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/indexes-for-full-text-search.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/introduction/neo4j-databases-graphs.adoc
  modules/ROOT/pages/keyword-glossary.adoc
Labels: 4.4, cherry-picked

#500 Restructure index section
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/indexes-for-full-text-search.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/keyword-glossary.adoc
  modules/ROOT/pages/query-tuning/indexes.adoc
  modules/ROOT/pages/syntax/spatial.adoc
Labels: team-cypher-operations, dev

#509 [Testing] Correct query plan for some operators (rollback) (#506)
  modules/ROOT/pages/execution-plans/operators.adoc
Labels: cherry-picked, 5.x

#508 BFS doesn't have an upper bound
  modules/ROOT/pages/execution-plans/operators.adoc
Labels: 5.7

#507 Add docs explaining MERGE + relationship uniqueness constraints
  modules/ROOT/pages/clauses/merge.adoc
Labels: 5.7

#511 Fix dbms admin images (#510)
  modules/ROOT/images/privileges_grant_and_deny_syntax_dbms_privileges.svg
  modules/ROOT/images/privileges_hierarchy_dbms.svg
Labels: cherry-picked, 5.x

#490 Re-add relationship constraint documentation
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/constraints/index.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/execution-plans/operators.adoc
  modules/ROOT/pages/introduction/cypher_neo4j.adoc
  modules/ROOT/pages/introduction/neo4j-databases-graphs.adoc
  modules/ROOT/pages/keyword-glossary.adoc
Labels: team-cypher-operations, dev, 5.7

#515 Add a clearer deprecation message for replacing the user of paths in the size() function.
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-surface, dev

#517 Updated deprecation message for size() function
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-picked, 5.x

#498 Update readme
  README.adoc
Labels: doc-ops

#519 Merge 5.7 PRs to 5.x
  antora.yml
  modules/ROOT/pages/administration/databases.adoc
  modules/ROOT/pages/clauses/call-subquery.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/constraints/index.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/execution-plans/operators.adoc
  modules/ROOT/pages/introduction/cypher_neo4j.adoc
  modules/ROOT/pages/introduction/neo4j-databases-graphs.adoc
  modules/ROOT/pages/keyword-glossary.adoc
  modules/ROOT/pages/query-tuning/query-options.adoc
Labels: 5.7

#520 Add 5.8 to antora.yml
  antora.yml
Labels: 5.8

#523 Add some initial documentation for query caches (#521)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/query-caches/index.adoc
  modules/ROOT/pages/query-caches/unified-query-caches.adoc
Labels: cherry-picked, 5.x

#525 Fix Query caches page
  modules/ROOT/pages/query-caches/index.adoc
Labels: cherry-picked, 5.x

#524 Fix Query caches page
  modules/ROOT/pages/query-caches/index.adoc
Labels: team-cypher-planner, dev, 5.7

#522 Add documentation for `AssertSameRelationship` logical plan
  modules/ROOT/pages/execution-plans/operator-summary.adoc
  modules/ROOT/pages/execution-plans/operators.adoc
Labels: team-cypher-planner, 5.8
