Repository neo4j/docs-cypher, pull requests merged in 2023-11, with the labels that each got.

#767 Add docs for the new nullIf() function
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/scalar.adoc
Labels: team-cypher-surface, dev, 5.14

#775 Add note for `ORDER BY` and guaranteed row-order
  modules/ROOT/pages/clauses/clause_composition.adoc
  modules/ROOT/pages/clauses/order-by.adoc
  modules/ROOT/pages/clauses/unwind.adoc
Labels: cherry-pick-this-to-5.x

#777 Add note for `ORDER BY` and guaranteed row-order (#775)
  modules/ROOT/pages/clauses/clause_composition.adoc
  modules/ROOT/pages/clauses/order-by.adoc
  modules/ROOT/pages/clauses/unwind.adoc
Labels: cherry-picked, 5.x

#778 Adding alias after 404 error
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: cherry-pick-this-to-5.x, dev

#779 Adding alias after 404 error (#778)
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: cherry-picked, 5.x

#785 bump exact version to 4.4.28
  antora.yml
Labels: 4.4, don't-cherry-pick

#780 Replaced deprecated pattern
  modules/ROOT/pages/styleguide.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, team-cypher-planner

#781 Add docs for new NODETACH keyword
  modules/ROOT/pages/clauses/delete.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-surface, 5.14

#764 Add docs for using exclamation mark short hand in types
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
Labels: team-cypher-surface, dev, 5.14

#787 Replaced deprecated pattern (#780)
  modules/ROOT/pages/styleguide.adoc
Labels: cherry-picked, 5.x

#788 4.4 cherry pick 780
  modules/ROOT/pages/styleguide.adoc
Labels: 4.4, cherry-picked

#789 Update Patterns with new var-length table and quantified relationship information
  modules/ROOT/pages/patterns/reference.adoc
Labels: cherry-pick-this-to-5.x

#791 fix and add links from Index and Constraints pages to Privileges section in Ops Manual
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/indexes-for-full-text-search.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/indexes-for-vector-search.adoc
Labels: cherry-pick-this-to-5.x

#792 Update Patterns with new var-length table and quantified relationship information (#789)
  modules/ROOT/pages/patterns/reference.adoc
Labels: cherry-picked, 5.x

#783 document new unicode deprecation notification for the future 5.15 rel…
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-surface, 5.14

#794 Update the links to syntax description section
  modules/ROOT/pages/clauses/listing-functions.adoc
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/indexes-for-full-text-search.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
Labels: team-cypher-operations

#795 Update the links to syntax description section (#794)
  modules/ROOT/pages/clauses/listing-functions.adoc
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/indexes-for-full-text-search.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
Labels: cherry-picked, 5.x

#797 5.x cherry pick to 5.14
  antora.yml
  modules/ROOT/pages/clauses/delete.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
Labels: 5.x, 5.14

#798 bump version to 5.15 for dev
  antora.yml
Labels: 5.15

#799 Improve documentation for suspended users
  modules/ROOT/pages/administration/access-control/manage-users.adoc
Labels: 4.4, cherry-picked

#786 Add deprecation for identifier characters
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/syntax/naming.adoc
Labels: team-cypher-surface, dev, 5.15

#782 Add docs for new ALL keyword
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/aggregating.adoc
Labels: team-cypher-surface, 5.15

#790 `SHOW INDEXES` can now be filtered on `VECTOR` same as other index type filtering
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/indexes-for-vector-search.adoc
Labels: team-cypher-operations, 5.15

#723 Improve Path Pattern Expression documentation
  modules/ROOT/pages/clauses/where.adoc
Labels: team-cypher-planner, dev

#801 Improve Path Pattern Expression documentation (#723)
  modules/ROOT/pages/clauses/where.adoc
Labels: cherry-picked, 5.x

#776 IS :: STRING NOT NULL as an index compatible predicate
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning/indexes.adoc
Labels: team-cypher-planner, 5.15

#802 Update `SHOW SETTINGS` output after bug fix
  modules/ROOT/pages/clauses/listing-settings.adoc
Labels: team-cypher-operations, 5.15
