Repository neo4j/docs-cypher, pull requests merged in 2024-11, with the labels that each got.

#1084 cip-190 deprecations
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-surface, 5.26, cherry-pick-this-to-cypher-25

#1057 Update Readme and yml files for Cypher 25
  .github/workflows/docs-pr-checks.yml
  .github/workflows/docs-teardown.yml
  README.adoc
  antora.yml
  preview.yml
  publish.yml
Labels: Cypher 25

#1090 Cypher 25 show commands updates
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/constraints/managing-constraints.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-operations, Cypher 25

#1097 Fix query plan versions
  modules/ROOT/pages/appendix/tutorials/advanced-query-tuning.adoc
  modules/ROOT/pages/appendix/tutorials/basic-query-tuning.adoc
  modules/ROOT/pages/appendix/tutorials/shortestpath-planning.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/index-hints.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/concepts.adoc
Labels: Cypher 25

#1099 Cherry pick 1096 (index provider deprecation)
  modules/ROOT/pages/constraints/managing-constraints.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/indexes/syntax.adoc
Labels: cherry-picked, Cypher 25

#1102 Update README to include documenting changes to language and GQL (#1100)
  README.adoc
Labels: Cypher 25

#1083 Further deprecations to options in CREATE DATABASE
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-operations, clustering, dev, 5.26

#1103 Change SHOW SETTINGS filter query example
  modules/ROOT/pages/clauses/listing-settings.adoc
Labels: 5.26, cherry-pick-this-to-cypher-25

#1104 Explain return values from vector functions
  modules/ROOT/pages/functions/vector.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1107 fix xref on LOAD CSV page
  modules/ROOT/pages/clauses/load-csv.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1106 Fix links to the Operations manual
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1108 Fix links to the Operations manual #1106
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-picked, 5.x

#1105 Document old deprecation for database naming
  modules/ROOT/pages/syntax/naming.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations, dev, cherry-pick-this-to-cypher-25

#1111 use quote in backticks rather than escape
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/styleguide.adoc
  modules/ROOT/pages/syntax/naming.adoc
  modules/ROOT/pages/syntax/reserved.adoc
Labels: 5.26, cherry-pick-this-to-cypher-25

#1110 Typo fix
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1098 Dynamic labels/types
  modules/ROOT/images/graph_match_clause.svg
  modules/ROOT/pages/appendix/gql-conformance/additional-cypher.adoc
  modules/ROOT/pages/clauses/create.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/clauses/remove.adoc
  modules/ROOT/pages/clauses/set.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: 5.26, cherry-pick-this-to-cypher-25

#1114 Cypher 25 Dynamic labels/types
  modules/ROOT/images/graph_match_clause.svg
  modules/ROOT/pages/appendix/gql-conformance/additional-cypher.adoc
  modules/ROOT/pages/clauses/create.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/clauses/remove.adoc
  modules/ROOT/pages/clauses/set.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-picked, Cypher 25

#1115 Fix vector config performance suggestion
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1118 Update the version number to 4.4.39
  antora.yml
Labels: 4.4, don't-cherry-pick

#1116 add complete fulltext stop words and clarify populating state
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/full-text-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1119 Fix failing query example
  modules/ROOT/pages/appendix/gql-conformance/additional-cypher.adoc
Labels: 5.26, cherry-pick-this-to-cypher-25

#1120 Document the availability of graph.byelementid on standard databases
  modules/ROOT/pages/appendix/gql-conformance/additional-cypher.adoc
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/graph.adoc
Labels: 5.26, cherry-pick-this-to-cypher-25

#1113 UNION ordering undeprecated
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-surface, dev, 5.26, cherry-pick-this-to-cypher-25

#1117 Add cheat sheet tags for dynamic labels/types
  modules/ROOT/pages/clauses/create.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/merge.adoc
Labels: 5.26, cherry-pick-this-to-cypher-25

#1126 New operator groupings
  modules/ROOT/pages/planning-and-tuning/execution-plans.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning.adoc
Labels: Cypher 25
