Repository neo4j/docs-cypher, pull requests merged in 2024-08, with the labels that each got.

#1010 Add TIME ZONE alias
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
Labels: team-cypher-surface, 5.23

#1011 Fix result format of relationships function
  modules/ROOT/pages/functions/list.adoc
Labels: cherry-pick-this-to-5.x

#1012 Fix result format of relationships function (#1011)
  modules/ROOT/pages/functions/list.adoc
Labels: cherry-picked, 5.x

#990 Document Variable Scope Clause
  modules/ROOT/images/call_subquery_graph.svg
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/genai-integrations.adoc
  modules/ROOT/pages/patterns/shortest-paths.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/subqueries/call-subquery.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
Labels: team-cypher-surface, 5.23

#1014 Fix typos on parsing page
  modules/ROOT/pages/syntax/parsing.adoc
Labels: cherry-pick-this-to-5.x

#1013 Add further considerations for CASE expressions
  modules/ROOT/pages/queries/case.adoc
Labels: team-cypher-surface, dev

#1016 Remove link to Cartesian CRSs
  modules/ROOT/pages/values-and-types/spatial.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#1017 Fix typo in Patterns reference
  modules/ROOT/pages/patterns/reference.adoc
Labels: cherry-pick-this-to-5.x

#1015 Add token privilege notes
  modules/ROOT/pages/administration/access-control/database-administration.adoc
  modules/ROOT/pages/administration/access-control/manage-privileges.adoc
  modules/ROOT/pages/administration/access-control/privileges-writes.adoc
Labels: 4.4

#1006 adding health warning about insecure protocols for LOAD CSV
  modules/ROOT/pages/clauses/load-csv.adoc
Labels: team-cypher-operations, dev, 5.23

#1018 fix GQL table and update on CALL
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
Labels: 5.23

#1020 link description correction
  modules/ROOT/pages/clauses/load-csv.adoc
Labels: dev, 5.23

#1019 Remove Enterprise Edition label from GenAI plugin page
  modules/ROOT/pages/genai-integrations.adoc
Labels: 5.23

#1021 Update GQL wording
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/unsupported-mandatory.adoc
Labels: cherry-pick-this-to-5.x

#1009 Add new vector index settings
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/indexes/syntax.adoc
Labels: 5.23

#1023 Correct documentation on comparing spatial values
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/syntax/operators.adoc
Labels: cherry-pick-this-to-5.x

#1026 Add information about Text indexes and dictionary variables
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
Labels: cherry-pick-this-to-5.x

#1028 Clarify text index use
  modules/ROOT/pages/query-tuning/indexes.adoc
Labels: 4.4

#1029 Add alias for index page
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
Labels: cherry-pick-this-to-5.x

#1031 5.23 publish
  antora.yml
  modules/ROOT/images/call_subquery_graph.svg
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/genai-integrations.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/indexes/syntax.adoc
  modules/ROOT/pages/patterns/shortest-paths.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/subqueries/call-subquery.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
  package-lock.json
  package.json
Labels: 5.x, 5.23

#972 Add docs on dynamic properties
  modules/ROOT/images/graph_remove_clause.svg
  modules/ROOT/images/graph_set_clause.svg
  modules/ROOT/pages/clauses/remove.adoc
  modules/ROOT/pages/clauses/set.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-surface, 5.24

#1025 Add note clarifying DELETE does not free up disk space
  modules/ROOT/pages/clauses/delete.adoc
Labels: cherry-pick-this-to-5.x

#1024 Add new Function detail tables (inluding new argument descriptions)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/functions/aggregating.adoc
  modules/ROOT/pages/functions/database.adoc
  modules/ROOT/pages/functions/graph.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/list.adoc
  modules/ROOT/pages/functions/load-csv.adoc
  modules/ROOT/pages/functions/mathematical-logarithmic.adoc
  modules/ROOT/pages/functions/mathematical-numeric.adoc
  modules/ROOT/pages/functions/mathematical-trigonometric.adoc
  modules/ROOT/pages/functions/predicate.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/functions/spatial.adoc
  modules/ROOT/pages/functions/string.adoc
  modules/ROOT/pages/functions/temporal/duration.adoc
  modules/ROOT/pages/functions/temporal/index.adoc
  modules/ROOT/pages/functions/vector.adoc
Labels: cherry-pick-this-to-5.x
