Repository neo4j/docs-cypher, pull requests merged in 2024-09, with the labels that each got.

#1027 Standalone Order by, Skip/Offset, and Limit
  modules/ROOT/images/graph_limit_clause.svg
  modules/ROOT/images/graph_order_by_clause.svg
  modules/ROOT/images/graph_skip_clause.svg
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/limit.adoc
  modules/ROOT/pages/clauses/order-by.adoc
  modules/ROOT/pages/clauses/skip.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-surface, 5.24

#1008 Add azure import example
  modules/ROOT/pages/clauses/load-csv.adoc
Labels: 5.24

#1037 LOAD CSV fixes
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: 5.24

#1035 Add brittleness information to id()/elementId() functions
  modules/ROOT/pages/clauses/order-by.adoc
  modules/ROOT/pages/functions/scalar.adoc
Labels: cherry-pick-this-to-5.x

#1038 fix CALL query in clause composition page
  modules/ROOT/pages/clauses/clause-composition.adoc
Labels: cherry-pick-this-to-5.x

#1033 Document Cypher features that are not in GQL
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/appendix/gql-conformance/additional-cypher.adoc
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
Labels: 5.24

#1043 Fix plans for Repeat(trail) and NullifyMetaData
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: 5.24

#1034 Document OPTIONAL CALL
  modules/ROOT/images/call_procedure.svg
  modules/ROOT/pages/clauses/call.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/subqueries/call-subquery.adoc
Labels: 5.24

#1045 Update the version to 4.4.37
  antora.yml
Labels: 4.4

#1036 Added `DROP DATABASE name CASCADE ALIASES`
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-operations, 5.24

#1042 adding Auth Providers to deprecations-additions-removals-compatibility
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-operations, 5.24

#1049 5.24 publish
  antora.yml
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/call_procedure.svg
  modules/ROOT/images/graph_limit_clause.svg
  modules/ROOT/images/graph_order_by_clause.svg
  modules/ROOT/images/graph_remove_clause.svg
  modules/ROOT/images/graph_set_clause.svg
  modules/ROOT/images/graph_skip_clause.svg
  modules/ROOT/pages/appendix/gql-conformance/additional-cypher.adoc
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/clauses/call.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/limit.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/order-by.adoc
  modules/ROOT/pages/clauses/remove.adoc
  modules/ROOT/pages/clauses/set.adoc
  modules/ROOT/pages/clauses/skip.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/subqueries/call-subquery.adoc
  package-lock.json
  package.json
Labels: 5.x, 5.24

#1050 Update antora for 5.25
  antora.yml
Labels: 5.25

#1051 Fix optional call link
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-pick-this-to-5.x, 5.24
