Repository neo4j/docs-cypher, pull requests merged in 2024-04, with the labels that each got.

#938 Update the exact version to 4.4.32
  antora.yml
Labels: 4.4

#939 fix query plans following updates to Eagerness
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: 5.19

#932 S3 URI support for LOAD CSV
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: 5.19

#941 Remove link to header that does not exist.
  modules/ROOT/pages/appendix/tutorials/advanced-query-tuning.adoc
Labels: cherry-pick-this-to-5.x, dev

#942 Clean up labels on additions & deprecations page (5.0 and forward)
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: 5.19

#940 FTP URL example for LOAD CSV
  modules/ROOT/pages/clauses/load-csv.adoc
Labels: cherry-pick-this-to-5.x

#943 Update VertexAI model and parameter support
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/genai-integrations.adoc
Labels: 5.19

#945 5.19 publish
  .github/workflows/docs-branch-checks.yml
  .gitignore
  antora.yml
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clauses/call.adoc
  modules/ROOT/pages/clauses/create.adoc
  modules/ROOT/pages/clauses/finish.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/clauses/set.adoc
  modules/ROOT/pages/clauses/union.adoc
  modules/ROOT/pages/clauses/unwind.adoc
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/genai-integrations.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/full-text-indexes.adoc
  modules/ROOT/pages/planning-and-tuning/execution-plans.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/syntax/parameters.adoc
  package-lock.json
  package.json
Labels: 5.19

#946 Update antora
  antora.yml
Labels: 5.20

#936 New Trim functions
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/string.adoc
Labels: team-cypher-surface, 5.20

#944 Add table of JVM to Unicode
  modules/ROOT/pages/syntax/parsing.adoc
Labels: cherry-pick-this-to-5.x

#952 Update the exact version to 4.4.33
  antora.yml
Labels: 4.4

#951 GQL conformance documentation
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/appendix/gql-conformance/analogous-cypher.adoc
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/appendix/gql-conformance/unsupported-mandatory.adoc
Labels: cherry-pick-this-to-5.x
