Repository neo4j/docs-cypher, pull requests merged in 2024-05, with the labels that each got.

#950 Deprecate cross-reference in MERGE clause
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-planner, 5.20

#955 Add btrim() to GQL compliance
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
Labels: 5.20

#957 Update the version number to 4.4.34
  antora.yml
Labels: 4.4

#956 Remove non-local variable restriction docs
  modules/ROOT/pages/patterns/reference.adoc
Labels: 5.20

#954 New vector index page
  modules/ROOT/images/vector_index_graph.svg
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
Labels: cherry-pick-this-to-5.x

#962 Vector index page clean up
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
Labels: cherry-pick-this-to-5.x

#967 5.20 publish
  antora.yml
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/string.adoc
  modules/ROOT/pages/patterns/reference.adoc
Labels: 5.20

#966 Update parsing.adoc
  modules/ROOT/pages/syntax/parsing.adoc
Labels: cherry-pick-this-to-dev

#968 Update antora for 5.21
  antora.yml
Labels: 5.21

#948 Add deprecatedBy column info to SHOW FUNCTIONS/PROCEDURES
  modules/ROOT/pages/clauses/listing-functions.adoc
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-surface, dev, 5.21

#969 SHOW SETTINGS 5.21 fix
  modules/ROOT/pages/clauses/listing-settings.adoc
Labels: 5.21

#960 Add docs for GQL fold aliases
  modules/ROOT/pages/appendix/gql-conformance/unsupported-mandatory.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/string.adoc
Labels: team-cypher-surface, 5.21

#965 Further GQL documentation
  modules/ROOT/pages/clauses/create.adoc
  modules/ROOT/pages/clauses/delete.adoc
  modules/ROOT/pages/clauses/finish.adoc
  modules/ROOT/pages/clauses/union.adoc
  modules/ROOT/pages/functions/aggregating.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/patterns/concepts.adoc
  modules/ROOT/pages/patterns/reference.adoc
  modules/ROOT/pages/syntax/operators.adoc
Labels: cherry-pick-this-to-5.x

#971 Fix SHOW TRANSACTIONS tables
  modules/ROOT/pages/clauses/transaction-clauses.adoc
Labels: cherry-pick-this-to-5.x
