Repository neo4j/docs-cypher, pull requests merged in 2024-03, with the labels that each got.

#899 Update comment about all available types under list of allowed types for property type constraints
  modules/ROOT/pages/constraints/examples.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-operations, dev

#881 Page aliases fix for version selector
  modules/.DS_Store
  modules/ROOT/pages/indexes/search-performance-indexes/index-hints.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/overview.adoc
  modules/ROOT/pages/indexes/semantic-indexes/full-text-indexes.adoc
  modules/ROOT/pages/planning-and-tuning/execution-plans.adoc
  modules/ROOT/pages/planning-and-tuning/operators/index.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/index.adoc
Labels: cherry-pick-this-to-dev

#904 Update link to CALL in tx page from DELETE page
  modules/ROOT/pages/clauses/delete.adoc
Labels: cherry-pick-this-to-5.x

#905 Update link to CALL in tx page from DELETE page (#904)
  modules/ROOT/pages/clauses/delete.adoc
Labels: cherry-picked, 5.x

#903 Page aliases fix for version selector (#881)
  modules/.DS_Store
  modules/ROOT/pages/indexes/search-performance-indexes/index-hints.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/overview.adoc
  modules/ROOT/pages/indexes/semantic-indexes/full-text-indexes.adoc
  modules/ROOT/pages/planning-and-tuning/execution-plans.adoc
  modules/ROOT/pages/planning-and-tuning/operators/index.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/index.adoc
Labels: cherry-picked, dev

#907 Remove DS store
  modules/.DS_Store
Labels: cherry-pick-this-to-5.x

#908 Remove DS store (#907)
  modules/.DS_Store
Labels: cherry-picked, 5.x

#909 Cherry-pick PRs 892 + 893
  modules/ROOT/pages/syntax/comments.adoc
  modules/ROOT/pages/syntax/parsing.adoc
Labels: cherry-picked, 5.x

#910 Change new[5.17] labels to text in index and constraints pages.
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/full-text-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/indexes/syntax.adoc
Labels: cherry-pick-this-to-5.x

#911 Change new[5.17] labels to text in index and constraints pages. (#910)
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/full-text-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/indexes/syntax.adoc
Labels: cherry-picked, 5.x

#914 typo fix
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-pick-this-to-5.x

#915 typo fix (#914)
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-picked, 5.x

#901 Fix CASE example
  modules/ROOT/pages/queries/case.adoc
Labels: team-cypher-surface, 5.18

#887 LOAD CSV improvements
  modules/ROOT/pages/clauses/load-csv.adoc
Labels: cherry-pick-this-to-5.x

#916 add results to 4.4 tutorial
  modules/ROOT/pages/introduction/cypher_tutorial.adoc
Labels: 4.4

#913 Document vector similarity functions
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/vector.adoc
Labels: 5.18

#912 Document AzureOpenAI and dimensions parameter support in GenAI plugin
  modules/ROOT/pages/genai-integrations.adoc
Labels: 5.18

#917 New roles to display new/deprecated content
  modules/ROOT/pages/clauses/create.adoc
  modules/ROOT/pages/clauses/delete.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/constraints/index.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/functions/database.adoc
  modules/ROOT/pages/functions/graph.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/functions/string.adoc
  modules/ROOT/pages/genai-integrations.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/patterns/concepts.adoc
  modules/ROOT/pages/patterns/reference.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning/query-options.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/concepts.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/reference.adoc
  modules/ROOT/pages/queries/case.adoc
  modules/ROOT/pages/subqueries/collect.adoc
  modules/ROOT/pages/subqueries/count.adoc
  modules/ROOT/pages/subqueries/existential.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/values-and-types/type-predicate.adoc
Labels: 5.18

#920 Vector 2.0 documentation changes
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/indexes/syntax.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: team-cypher-operations, 5.18

#922 5.18 publish
  .github/CODEOWNERS
  antora.yml
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clauses/create.adoc
  modules/ROOT/pages/clauses/delete.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/constraints/index.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/database.adoc
  modules/ROOT/pages/functions/graph.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/functions/string.adoc
  modules/ROOT/pages/functions/vector.adoc
  modules/ROOT/pages/genai-integrations.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/indexes/syntax.adoc
  modules/ROOT/pages/patterns/concepts.adoc
  modules/ROOT/pages/patterns/reference.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning/query-options.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/concepts.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/reference.adoc
  modules/ROOT/pages/queries/case.adoc
  modules/ROOT/pages/subqueries/collect.adoc
  modules/ROOT/pages/subqueries/count.adoc
  modules/ROOT/pages/subqueries/existential.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/values-and-types/type-predicate.adoc
  package-lock.json
  package.json
Labels: 5.18

#923 Update antora for 5.19
  antora.yml
Labels: 5.19

#898 Finish clause
  .gitignore
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clauses/finish.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-surface, 5.19

#926 Remove test-skip role on Understanding Execution Plans page
  modules/ROOT/pages/planning-and-tuning/execution-plans.adoc
Labels: cherry-pick-this-to-5.x

#928 Remove incorrect test-fail role on Constraints page
  modules/ROOT/pages/constraints/examples.adoc
Labels: cherry-pick-this-to-5.x

#927 Style guide fixes
  modules/ROOT/pages/styleguide.adoc
Labels: cherry-pick-this-to-5.x

#929 Fix parallel runtime reference page example
  modules/ROOT/pages/planning-and-tuning/runtimes/reference.adoc
Labels: cherry-pick-this-to-5.x

#921 New Concatenation Operator `||`
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/syntax/operators.adoc
Labels: team-cypher-surface, 5.19

#934 Fix genai query variable
  modules/ROOT/pages/genai-integrations.adoc
Labels: cherry-pick-this-to-5.x

#935 Fix image on subquery pages
  modules/ROOT/images/subqueries_graph.svg
Labels: cherry-pick-this-to-5.x

#924 UNION DISTINCT
  modules/ROOT/pages/clauses/union.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: 5.19
