Repository neo4j/docs-cypher, pull requests merged in 2024-06, with the labels that each got.

#958 Describe query option to infer labels.
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning.adoc
Labels: team-cypher-planner, 5.21

#975 add fullstops
  modules/ROOT/pages/clauses/listing-settings.adoc
Labels: 5.21

#976 Replacing URLs with underscore with hyphens
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clauses/clause-composition.adoc
  modules/ROOT/pages/clauses/union.adoc
  modules/ROOT/pages/introduction/cypher-aura.adoc
  modules/ROOT/pages/introduction/cypher-neo4j.adoc
  modules/ROOT/pages/introduction/cypher-overview.adoc
  modules/ROOT/pages/introduction/index.adoc
  modules/ROOT/pages/patterns/reference.adoc
  modules/ROOT/pages/planning-and-tuning/execution-plans.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/queries/basic.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#977 Replacing URLs with underscore with hyphens (#976)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clauses/clause-composition.adoc
  modules/ROOT/pages/clauses/union.adoc
  modules/ROOT/pages/introduction/cypher-aura.adoc
  modules/ROOT/pages/introduction/cypher-neo4j.adoc
  modules/ROOT/pages/introduction/cypher-overview.adoc
  modules/ROOT/pages/introduction/index.adoc
  modules/ROOT/pages/patterns/reference.adoc
  modules/ROOT/pages/planning-and-tuning/execution-plans.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/queries/basic.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
Labels: cherry-picked

#978 Replacing URLs with underscore with hyphens (#976)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/administration/access-control/dbms-administration.adoc
  modules/ROOT/pages/clauses/call-subquery.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/introduction/cypher-aura.adoc
  modules/ROOT/pages/introduction/cypher-neo4j.adoc
  modules/ROOT/pages/introduction/cypher-overview.adoc
  modules/ROOT/pages/introduction/cypher-tutorial.adoc
  modules/ROOT/pages/introduction/index.adoc
Labels: cherry-picked

#863 Documentation for SHORTEST
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/path_pattern_motif.svg
  modules/ROOT/images/patterns_qpp_predicates.svg
  modules/ROOT/images/patterns_second_shortest_paths.svg
  modules/ROOT/images/patterns_shortest_graph.svg
  modules/ROOT/images/patterns_shortest_graph_pattern1.svg
  modules/ROOT/images/patterns_shortest_graph_pattern2.svg
  modules/ROOT/images/patterns_shortest_tie.svg
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/appendix/tutorials/index.adoc
  modules/ROOT/pages/appendix/tutorials/shortestpath-planning.adoc
  modules/ROOT/pages/clauses/foreach.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/patterns/concepts.adoc
  modules/ROOT/pages/patterns/fixed-length-patterns.adoc
  modules/ROOT/pages/patterns/index.adoc
  modules/ROOT/pages/patterns/non-linear-patterns.adoc
  modules/ROOT/pages/patterns/primer.adoc
  modules/ROOT/pages/patterns/reference.adoc
  modules/ROOT/pages/patterns/shortest-paths.adoc
  modules/ROOT/pages/patterns/variable-length-patterns.adoc
  modules/ROOT/pages/planning-and-tuning/execution-plans.adoc
  modules/ROOT/pages/planning-and-tuning/operators/index.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/queries/basic.adoc
  modules/ROOT/pages/queries/concepts.adoc
  modules/ROOT/pages/syntax/operators.adoc
Labels: team-cypher-planner, 5.21

#979 Reverse order of Euclidean and cosine
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/vector.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
Labels: cherry-pick-this-to-5.x

#974 Document CALL IN CONCURRENT TRANSACTIONS
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/concepts.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
Labels: 5.21

#982 Add new operator SubtractionNodeByLabelsScan
  modules/ROOT/pages/planning-and-tuning/operators/index.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: team-cypher-runtime, 5.21

#980 LOAD CSV support for Google Cloud Storage URIs
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: 5.21

#983 Organizing clauses and subqueries in alphabetical order
  modules/ROOT/content-nav.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, dev

#985 Organizing clauses and subqueries in alphabetical order (#983)
  modules/ROOT/content-nav.adoc
Labels: cherry-picked, 5.x

#987 Organizing clauses and subqueries in alphabetical order (#983)
  modules/ROOT/content-nav.adoc
Labels: 4.4, cherry-picked

#993 Update antora for 5.22
  antora.yml
Labels: 5.22
