Repository neo4j/docs-cypher, pull requests merged in 2024-07, with the labels that each got.

#995 Fix typo
  modules/ROOT/pages/queries/concepts.adoc
Labels: cherry-pick-this-to-5.x

#996 Add Post-union processing example to UNION page
  modules/ROOT/images/graph_union_clause.svg
  modules/ROOT/pages/clauses/union.adoc
Labels: cherry-pick-this-to-5.x

#998 update the exact version to 4.4.35
  antora.yml
Labels: 4.4

#991 Add mandatory GQL features
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/appendix/gql-conformance/analogous-cypher.adoc
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/appendix/gql-conformance/unsupported-mandatory.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
Labels: 5.21

#999 Fix vector header
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
Labels: cherry-pick-this-to-5.x

#1002 Add a notice for directedUnionRelationshipTypeScans
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: team-cypher-planner

#1007 Update the exact version to 4.4.36
  antora.yml
Labels: 4.4
