Repository neo4j/docs-cypher, pull requests merged in 2024-12, with the labels that each got.

#1127 Add page-alias to CALL subquery page
  modules/ROOT/pages/subqueries/call-subquery.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1125 Cheat sheet tags for patterns and label expressions
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/patterns/fixed-length-patterns.adoc
  modules/ROOT/pages/patterns/non-linear-patterns.adoc
  modules/ROOT/pages/patterns/shortest-paths.adoc
  modules/ROOT/pages/patterns/variable-length-patterns.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1135 Update the version to 4.4.40
  antora.yml
Labels: 4.4

#1136 Several small fixes to query plan ascii and links
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1137 Add Performance caveats section to Merge/Match dynamic labels section
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/merge.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1140 Change release version to 2025.02
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: Cypher 25

#1141 Add seedRestoreUntil option
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: Cypher 25, 2025.02

#1124 Allow for parameters in SHORTEST
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/patterns/reference.adoc
  modules/ROOT/pages/patterns/shortest-paths.adoc
Labels: team-cypher-surface, Cypher 25, 2025.02
