Repository neo4j/docs-cypher, pull requests merged in 2024-10, with the labels that each got.

#1054 Fix links to Auth providers in Ops Manual
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-pick-this-to-5.x

#1058 Update 4.4 version to 4.4.38
  antora.yml
Labels: 4.4

#1060 Clarify CALL subquery ambiguities
  modules/ROOT/images/call_subquery_graph.svg
  modules/ROOT/pages/subqueries/call-subquery.adoc
Labels: cherry-pick-this-to-5.x

#1047 Deprecate `existingDataSeedInstance` option to CREATE DATABASE
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-operations, dev, 5.25

#1064 clarify point.distance function
  modules/ROOT/pages/appendix/gql-conformance/additional-cypher.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/spatial.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1065 fix functions table (Logarithmic was missing)
  modules/ROOT/pages/functions/index.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1041 Restructure Constraints section
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/appendix/gql-conformance/additional-cypher.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/clauses/optional-match.adoc
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/constraints/index.adoc
  modules/ROOT/pages/constraints/managing-constraints.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/introduction/cypher-neo4j.adoc
  modules/ROOT/pages/introduction/cypher-overview.adoc
  modules/ROOT/pages/patterns/shortest-paths.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
Labels: cherry-pick-this-to-5.x

#1066 Add new label to type constraints and page alias
  modules/ROOT/pages/constraints/index.adoc
  modules/ROOT/pages/constraints/managing-constraints.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1059 Document unicode changes for Cypher 25
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/syntax/parsing.adoc
Labels: team-cypher-surface, dev, Cypher 25

#1062 Document change in behaviour for db.schema.nodeTypeProperties() and db.schema.relTypeProperties()
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-surface, Cypher 25

#1067 Cherry-pick new Constraints section to Cypher 25
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/appendix/gql-conformance/additional-cypher.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/clauses/optional-match.adoc
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/constraints/index.adoc
  modules/ROOT/pages/constraints/managing-constraints.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/introduction/cypher-neo4j.adoc
  modules/ROOT/pages/introduction/cypher-overview.adoc
  modules/ROOT/pages/patterns/shortest-paths.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
Labels: Cypher 25

#1068 Fix typo and change auradb enterprise to auradb virtual dedicated cloud on parallel runtime page
  modules/ROOT/pages/planning-and-tuning/runtimes/reference.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1071 Intro with a link to ops manual for cloud URI section
  modules/ROOT/pages/clauses/load-csv.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1072 Make Cypher Manual AuraDB Business Critical aware
  modules/ROOT/pages/introduction/cypher-aura.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1074 Fix remaining examples of CALL subqueries without variable scope clause
  modules/ROOT/pages/clauses/union.adoc
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/functions/graph.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1056 Cypher 25: Remove 5.x "Introduced in" labels and in-text notifications
  modules/ROOT/pages/appendix/tutorials/advanced-query-tuning.adoc
  modules/ROOT/pages/clauses/call.adoc
  modules/ROOT/pages/clauses/clause-composition.adoc
  modules/ROOT/pages/clauses/create.adoc
  modules/ROOT/pages/clauses/delete.adoc
  modules/ROOT/pages/clauses/finish.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/limit.adoc
  modules/ROOT/pages/clauses/listing-functions.adoc
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/clauses/order-by.adoc
  modules/ROOT/pages/clauses/remove.adoc
  modules/ROOT/pages/clauses/set.adoc
  modules/ROOT/pages/clauses/skip.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/clauses/union.adoc
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/functions/aggregating.adoc
  modules/ROOT/pages/functions/database.adoc
  modules/ROOT/pages/functions/graph.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/functions/string.adoc
  modules/ROOT/pages/functions/vector.adoc
  modules/ROOT/pages/genai-integrations.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/full-text-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/indexes/syntax.adoc
  modules/ROOT/pages/patterns/reference.adoc
  modules/ROOT/pages/patterns/shortest-paths.adoc
  modules/ROOT/pages/patterns/variable-length-patterns.adoc
  modules/ROOT/pages/planning-and-tuning/operators/index.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/concepts.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/reference.adoc
  modules/ROOT/pages/queries/basic.adoc
  modules/ROOT/pages/queries/case.adoc
  modules/ROOT/pages/subqueries/call-subquery.adoc
  modules/ROOT/pages/subqueries/collect.adoc
  modules/ROOT/pages/subqueries/count.adoc
  modules/ROOT/pages/subqueries/existential.adoc
  modules/ROOT/pages/subqueries/index.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
  modules/ROOT/pages/values-and-types/spatial.adoc
  modules/ROOT/pages/values-and-types/temporal.adoc
  modules/ROOT/pages/values-and-types/type-predicate.adoc
Labels: Cypher 25

#1075 Fix SHOW CONSTRAINTS table
  modules/ROOT/pages/constraints/managing-constraints.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1076 Aura update for parallel runtime
  modules/ROOT/pages/planning-and-tuning/runtimes/reference.adoc
Labels: 5.25, cherry-pick-this-to-cypher-25

#1077 Document max identifier length
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/syntax/naming.adoc
Labels: 5.25

#1078 Document identfier max length
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/syntax/naming.adoc
Labels: cherry-picked, Cypher 25

#1079 Add missing curly bracket
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: 5.25

#1069 Document removal of allowing nodes and rels on RHS of SET properties …
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-surface, Cypher 25

#1080 Update MATCH page
  modules/ROOT/images/graph_match_clause.svg
  modules/ROOT/pages/clauses/match.adoc
Labels: cherry-pick-this-to-5.x, auto-cherry-pick-to-cypher-25

#1085 Small fix to MATCH
  modules/ROOT/pages/clauses/match.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1086 Remove mentions of Neo4j 6.0
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/syntax/naming.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1088 Remove mentions of Neo4j 6.0
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/syntax/naming.adoc
Labels: Cypher 25

#1089 5.25 publish
  antora.yml
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/reference.adoc
  modules/ROOT/pages/syntax/naming.adoc
  package-lock.json
  package.json
Labels: 5.25

#1063 Document change in behaviour for db.schema.nodeTypeProperties() and db.schema.relTypeProperties()
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-surface, 5.26

#1092 Cherry pick 1063
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-picked, Cypher 25, 5.26

#1070 Adding the new functionality of property-based access control to list of new features
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-operations, 5.26, cherry-pick-this-to-cypher-25

#1093 Cherry pick 1070
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-picked, Cypher 25, 5.26

#1082 Add entry in additions/removals about parameters in CREATE/ALTER DB TOPOLOGY
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-operations, 5.26, cherry-pick-this-to-cypher-25

#1094 cherry pick 1082
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-picked, Cypher 25, 5.26

#1095 Fix version exact roles
  modules/ROOT/pages/appendix/tutorials/advanced-query-tuning.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25
