Repository neo4j/docs-cypher, pull requests merged in 2024-02, with the labels that each got.

#878 update exact version to 4.4.30
  antora.yml
Labels: 4.4

#882 Add genAI integrations
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/genai-integrations.adoc
Labels: cherry-pick-this-to-5.x, Aura, 5.16

#884 Add genAI integrations (#882)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/genai-integrations.adoc
Labels: cherry-picked, 5.x

#885 Add the genai.vector.encode function to the available functions
  modules/ROOT/pages/functions/index.adoc
Labels: cherry-pick-this-to-5.x

#886 Add the genai.vector.encode function to the available functions (#885)
  modules/ROOT/pages/functions/index.adoc
Labels: cherry-picked, 5.x

#880 Document the new notifications
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/full-text-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/indexes/syntax.adoc
Labels: team-cypher-operations, 5.17

#889 Document that the GenAI plugin is available on prem as well
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/genai-integrations.adoc
Labels: 5.17

#891 Fix bad GenAI batching example
  modules/ROOT/pages/genai-integrations.adoc
Labels: cherry-pick-this-to-5.x, 5.16, 5.17

#894 Fix bad GenAI batching example (#891)
  modules/ROOT/pages/genai-integrations.adoc
Labels: cherry-picked, 5.x

#867 Document INSERT and the addition of & to CREATE and MERGE
  modules/ROOT/pages/clauses/create.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-surface, 5.18

#892 Add docs on newline chars in Cypher
  modules/ROOT/pages/syntax/parsing.adoc
Labels: team-cypher-surface, dev

#893 Add docs on multiline comments
  modules/ROOT/pages/syntax/comments.adoc
Labels: team-cypher-surface, dev

#896 CALL IN TRANSACTIONS on composite databases
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
Labels: dev, team-cypher-composite, 5.18
