Repository neo4j/docs-cypher, pull requests merged in 2024-01, with the labels that each got.

#824 db.index.vector.createNodeIndex replaced by CREATE VECTOR INDEX
  modules/ROOT/pages/indexes-for-vector-search.adoc
Labels: cherry-pick-this-to-5.x

#825 db.index.vector.createNodeIndex replaced by CREATE VECTOR INDEX (#824)
  modules/ROOT/pages/indexes-for-vector-search.adoc
Labels: cherry-picked, 5.x

#826 Update style-guide advice about functions
  modules/ROOT/pages/styleguide.adoc
Labels: cherry-pick-this-to-5.x

#827 Update style-guide advice about functions (#826)
  modules/ROOT/pages/styleguide.adoc
Labels: cherry-picked, 5.x

#770 New Indexes chapter
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/full_text_graph.svg
  modules/ROOT/images/using_indexes_example_graph.svg
  modules/ROOT/pages/appendix/tutorials/advanced-query-tuning.adoc
  modules/ROOT/pages/appendix/tutorials/basic-query-tuning.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/constraints/index.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/indexes-for-full-text-search.adoc
  modules/ROOT/pages/indexes-for-search-performance.adoc
  modules/ROOT/pages/indexes/index.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/index-hints.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/overview.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/full-text-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/overview.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/indexes/syntax.adoc
  modules/ROOT/pages/planning-and-tuning/index.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning/index.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning/indexes.adoc
  modules/ROOT/pages/values-and-types/spatial.adoc
Labels: Cypher Manual Restructure, 5.16

#831 Update elementId()
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/scalar.adoc
Labels: cherry-pick-this-to-5.x

#832 Update elementId() (#831)
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/scalar.adoc
Labels: cherry-picked, 5.x

#835 Add note to labels() function
  modules/ROOT/pages/functions/list.adoc
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#836 Add note to labels() function (#835)
  modules/ROOT/pages/functions/list.adoc
Labels: cherry-picked, 5.x

#837 Convert Constraint Types to headers
  modules/ROOT/pages/constraints/index.adoc
Labels: cherry-pick-this-to-dev

#838 Convert Constraint Types to headers (#837)
  modules/ROOT/pages/constraints/index.adoc
Labels: cherry-picked, dev

#840 Index chapter clean up
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/full-text-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/indexes/syntax.adoc
Labels: 5.16

#839 Add operators that are missing on the detail page
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-runtime

#842 More fixes to new index chapter
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
Labels: 5.16

#851 Update operator pages
  modules/ROOT/pages/planning-and-tuning/operators/index.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: cherry-pick-this-to-5.x

#854 Cherry Pick PRs 831 & 851
  modules/ROOT/pages/planning-and-tuning/operators/index.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: cherry-picked, 5.x

#857 Update year in yml files to 2024
  preview.yml
  publish.yml
Labels: cherry-pick-this-to-4.4, cherry-pick-this-to-5.x

#858 Update year in yml files to 2024 (#857)
  preview.yml
  publish.yml
Labels: cherry-picked, 5.x

#859 Update year in yml files to 2024 (#857)
  preview.yml
  publish.yml
Labels: 4.4, cherry-picked

#784 Add docs for new normalize function.
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/string.adoc
Labels: team-cypher-surface, 5.17

#804 Dev normalize predicate
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/string.adoc
  modules/ROOT/pages/syntax/operators.adoc
Labels: team-cypher-surface, dev, 5.17

#847 Add descriptions of partitioned operators.
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/planning-and-tuning/operators/index.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: team-cypher-runtime, 5.17

#841 Mention explicitly that unsignedInteger must not be larger than Long.MAX_VALUE.
  modules/ROOT/pages/patterns/reference.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-surface

#864 Mention explicitly that unsignedInteger must not be larger than Long.MAX_VALUE. (#841)
  modules/ROOT/pages/patterns/reference.adoc
Labels: cherry-picked, 5.x

#865 Fix broken links
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clauses/order-by.adoc
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/patterns/concepts.adoc
Labels: cherry-pick-this-to-5.x

#866 Fix broken links (#865)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clauses/order-by.adoc
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/patterns/concepts.adoc
Labels: cherry-picked, 5.x

#862 Update SHOW SETTINGS table to include `dbms.cluster.network.connect_timeout`
  modules/ROOT/pages/clauses/listing-settings.adoc
Labels: 5.17

#853 Update value types: `STRING`
  modules/ROOT/pages/clauses/call.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/constraints/examples.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/aggregating.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/list.adoc
  modules/ROOT/pages/functions/predicate.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/functions/string.adoc
  modules/ROOT/pages/functions/temporal/duration.adoc
  modules/ROOT/pages/functions/temporal/index.adoc
  modules/ROOT/pages/planning-and-tuning/operators/index.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/styleguide.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/syntax/parameters.adoc
  modules/ROOT/pages/syntax/parsing.adoc
  modules/ROOT/pages/values-and-types/lists.adoc
  modules/ROOT/pages/values-and-types/spatial.adoc
  modules/ROOT/pages/values-and-types/temporal.adoc
Labels: cherry-pick-this-to-5.x

#850 Fix some tests
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/patterns/concepts.adoc
  modules/ROOT/pages/styleguide.adoc
  modules/ROOT/pages/values-and-types/type-predicate.adoc
Labels: cherry-pick-this-to-5.x

#869 Fix some tests (#850)
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/patterns/concepts.adoc
  modules/ROOT/pages/styleguide.adoc
  modules/ROOT/pages/values-and-types/type-predicate.adoc
Labels: cherry-picked, 5.x

#870 Typo fix
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
Labels: cherry-pick-this-to-5.x

#871 Typo fix (#870)
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
Labels: cherry-picked, 5.x

#873 Fix indexes links
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
Labels: cherry-pick-this-to-5.x

#874 Fix indexes links (#873)
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
Labels: cherry-picked, 5.x

#875 Fix index query plan and add links on Syntax page
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/indexes/syntax.adoc
Labels: cherry-pick-this-to-5.x

#877 update dbms.cluster.discovery.resolver_type
  modules/ROOT/pages/clauses/listing-settings.adoc
Labels: cherry-pick-this-to-5.x

#879 update show settings tables(#877)
  modules/ROOT/pages/clauses/listing-settings.adoc
Labels: cherry-picked
