Repository neo4j/docs-cypher, pull requests merged in 2025-08, with the labels that each got.

#1347 Remove Neo4j version from PDF title
  modules/ROOT/pages/introduction/index.adoc
Labels: cherry-pick-to-cypher-25, cherry-pick-to-cypher-5

#1348 added select cypher versions link
  modules/ROOT/pages/patterns/variable-length-patterns.adoc
Labels: Cypher 25, Cypher 5

#1350 update antora for 2025.08
  antora.yml
Labels: 2025.08

#1351 Fix links to ops manual for select Cypher versions
  modules/ROOT/pages/queries/select-version.adoc
Labels: cherry-pick-to-cypher-25, cherry-pick-to-cypher-5

#1352 Fix broken links
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/introduction/cypher-aura.adoc
  modules/ROOT/pages/introduction/index.adoc
  modules/ROOT/pages/queries/select-version.adoc
Labels: cherry-pick-to-cypher-25, cherry-pick-to-cypher-5

#1353 Renaming overview.adoc to index
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clauses/delete.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/indexes/index.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/index.adoc
  modules/ROOT/pages/indexes/semantic-indexes/index.adoc
  modules/ROOT/pages/queries/basic.adoc
Labels: cherry-pick-to-cypher-25, cherry-pick-to-cypher-5

#1354 Renaming overview.adoc to index (#1353)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clauses/delete.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/indexes/index.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/index.adoc
  modules/ROOT/pages/indexes/semantic-indexes/index.adoc
  modules/ROOT/pages/queries/basic.adoc
Labels: cherry-picked

#1355 Renaming overview.adoc to index (#1353)
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/clauses/delete.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/indexes/index.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/index.adoc
  modules/ROOT/pages/indexes/semantic-indexes/index.adoc
  modules/ROOT/pages/queries/basic.adoc
Labels: cherry-picked, Cypher 5

#1357 `allReduce()` function
  modules/ROOT/images/graph-predicate-functions.svg
  modules/ROOT/images/predicate-function-example.svg
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/predicate.adoc
Labels: 2025.08

#1360 New operators for Dynamic values
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: 2025.08

#1366 Shortest path performance and planning for Cypher 5
  modules/ROOT/pages/patterns/shortest-paths.adoc
Labels: cherry-picked, Cypher 5

#1365 Clarify `indexes` return column for `SHOW TRANSACTIONS` when dynamic values are used
  modules/ROOT/pages/clauses/transaction-clauses.adoc
Labels: cherry-pick-to-cypher-25, cherry-pick-to-cypher-5

#1367 remove old shortest path tutorial
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/appendix/tutorials/index.adoc
  modules/ROOT/pages/appendix/tutorials/shortestpath-planning.adoc
Labels: cherry-pick-to-cypher-25, cherry-pick-to-cypher-5

#1371 Add another criteria for when SHORTEST queries are rewritten with to use legacy operator
  modules/ROOT/pages/patterns/shortest-paths.adoc
Labels: cherry-pick-to-cypher-25, cherry-pick-to-cypher-5

#1368 Fulltext index provider to 2.0 in SHOW FULLTEXT INDEX examples
  modules/ROOT/pages/indexes/semantic-indexes/full-text-indexes.adoc
Labels: cherry-pick-to-cypher-25, cherry-pick-to-cypher-5
