Repository neo4j/docs-cypher, pull requests merged in 2025-01, with the labels that each got.

#1143 Add dynamically referenced labels and types to allowed parameters
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/syntax/parameters.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1144 Add dynamically referenced labels and types to allowed parameters
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/syntax/parameters.adoc
Labels: cherry-picked, Cypher 25

#1145 document deprecation of graph names with unesacped dots in USE clauses
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-composite, 5.26, cherry-pick-this-to-cypher-25

#1148 Correct genai batchEncode example syntax
  modules/ROOT/pages/genai-integrations.adoc
Labels: cherry-pick-this-to-dev, cherry-pick-this-to-cypher-25

#1147 The Cypher query option `eagerAnalyzer` is deprecated
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-planner, cherry-pick-this-to-cypher-25, 2025.01

#1150 The Cypher query option eagerAnalyzer is deprecated #1147
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-picked, Cypher 25, 2025.01

#1152 Explain trigram indexing for text-2.0 provider
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1153 Explain trigram index for text indexes
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
Labels: cherry-picked, Cypher 25

#1146 Document lower bound restriction for shortestPath() and allShortestPath() functions
  modules/ROOT/pages/patterns/reference.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-planner, dev, cherry-pick-this-to-cypher-25

#1154 Hyphenation
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/patterns/fixed-length-patterns.adoc
  modules/ROOT/pages/patterns/reference.adoc
  modules/ROOT/pages/patterns/variable-length-patterns.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning.adoc
  modules/ROOT/pages/queries/basic.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1155 Change page-version attribute in external links to current
  modules/ROOT/pages/administration/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/additional-cypher.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/appendix/gql-conformance/unsupported-mandatory.adoc
  modules/ROOT/pages/appendix/tutorials/advanced-query-tuning.adoc
  modules/ROOT/pages/appendix/tutorials/basic-query-tuning.adoc
  modules/ROOT/pages/appendix/tutorials/shortestpath-planning.adoc
  modules/ROOT/pages/clauses/call.adoc
  modules/ROOT/pages/clauses/delete.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/listing-functions.adoc
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/constraints/managing-constraints.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/graph.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/functions/user-defined.adoc
  modules/ROOT/pages/genai-integrations.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/full-text-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/indexes/syntax.adoc
  modules/ROOT/pages/introduction/cypher-aura.adoc
  modules/ROOT/pages/introduction/cypher-neo4j.adoc
  modules/ROOT/pages/introduction/cypher-overview.adoc
  modules/ROOT/pages/introduction/index.adoc
  modules/ROOT/pages/patterns/reference.adoc
  modules/ROOT/pages/planning-and-tuning/execution-plans.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/reference.adoc
  modules/ROOT/pages/query-caches/index.adoc
  modules/ROOT/pages/query-caches/unified-query-caches.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
  modules/ROOT/pages/syntax/naming.adoc
  modules/ROOT/pages/syntax/parameters.adoc
  modules/ROOT/pages/values-and-types/maps.adoc
  modules/ROOT/pages/values-and-types/temporal.adoc
Labels: Cypher 25

#1130 Keyword priority
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/appendix/gql-conformance/unsupported-mandatory.adoc
  modules/ROOT/pages/syntax/index.adoc
  modules/ROOT/pages/syntax/keywords.adoc
  modules/ROOT/pages/syntax/reserved.adoc
  modules/ROOT/pages/syntax/variables.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1157 Clarify YIELD
  modules/ROOT/pages/clauses/call.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1159 clairfy Yield
  modules/ROOT/pages/clauses/call.adoc
Labels: cherry-picked, Cypher 25

#1160 Alias to new keywords page
  modules/ROOT/pages/syntax/keywords.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1163 Property type rephrase
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1164 fix antora for 2025.01
  antora.yml
  preview.yml
Labels: 2025.01

#1166 Fix failing query plans
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: cherry-pick-this-to-cypher-25, 2025.01

#1167 Table fixes, remove sitemap extension from playbook
  modules/ROOT/pages/clauses/call.adoc
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/functions/aggregating.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/values-and-types/temporal.adoc
  publish.yml
Labels: cherry-pick-this-to-cypher-25, 2025.01

#1168 Remove redundant antora attributes
  antora.yml
  modules/ROOT/pages/appendix/tutorials/advanced-query-tuning.adoc
  modules/ROOT/pages/appendix/tutorials/basic-query-tuning.adoc
  modules/ROOT/pages/appendix/tutorials/shortestpath-planning.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/index-hints.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/concepts.adoc
Labels: cherry-pick-this-to-cypher-25, 2025.01

#1169 Cypher 25 antora cherry-picks (#1164, 1167, 1168)
  antora.yml
  modules/ROOT/pages/clauses/call.adoc
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/functions/aggregating.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/values-and-types/temporal.adoc
  preview.yml
  publish.yml
Labels: cherry-picked, Cypher 25

#1156 Clarify DETACH DELETE
  modules/ROOT/pages/clauses/delete.adoc
  modules/ROOT/pages/queries/basic.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1162 add graph reference section to expressions
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/queries/expressions.adoc
Labels: team-cypher-composite, Cypher 25

#1173 CALL fix for cypher 25 docs
  modules/ROOT/pages/subqueries/call-subquery.adoc
Labels: Cypher 25

#1174 Remove invalid duration field
  modules/ROOT/pages/functions/temporal/duration.adoc
Labels: team-cypher-surface, dev

#1176 Revert changes to pattern query plans
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: cherry-pick-this-to-cypher-25, 2025.01

#1177 Better Unicode example on Parsing page
  modules/ROOT/pages/syntax/parsing.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25
