Repository neo4j/docs-cypher, pull requests merged in 2025-03, with the labels that each got.

#1191 New hyperbolic trig functions
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/mathematical-trigonometric.adoc
Labels: team-cypher-surface, Cypher 25

#1207 Document `LET`
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/let_clause.svg
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/let.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/syntax/keywords.adoc
Labels: Cypher 25

#1209 Update Operator reference in query-plan-eager.
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-planner, cherry-pick-this-to-cypher-25

#1211 Expressions/Mathematical operators
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/expressions/index.adoc
  modules/ROOT/pages/expressions/mathematical-operators.adoc
  modules/ROOT/pages/functions/mathematical-logarithmic.adoc
  modules/ROOT/pages/functions/mathematical-numeric.adoc
  modules/ROOT/pages/functions/mathematical-trigonometric.adoc
  modules/ROOT/pages/syntax/operators.adoc
Labels: Cypher 25

#1212 Fix link to dump files (/blob to /raw)
  modules/ROOT/pages/genai-integrations.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1214 Fix link to dump files (/blob to /raw) (#1212)
  modules/ROOT/pages/genai-integrations.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
Labels: cherry-picked, Cypher 25

#1213 document statement types
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/introduction/cypher-neo4j.adoc
Labels: cherry-pick-this-to-5.x, dev, team-cypher-composite, cherry-pick-this-to-cypher-25

#1216 tablefix
  modules/ROOT/pages/expressions/mathematical-operators.adoc
Labels: Cypher 25

#1215 String expressions
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/expressions/index.adoc
  modules/ROOT/pages/expressions/string-operators.adoc
  modules/ROOT/pages/functions/string.adoc
  modules/ROOT/pages/syntax/operators.adoc
Labels: Cypher 25

#1203 Document `ON ERROR RETRY`
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
Labels: cherry-pick-this-to-dev, Cypher 25, 2025.03

#1220 `ON ERROR RETRY` for 5 manual
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
Labels: cherry-picked, dev, 2025.03

#1221 Update to 4.4.42
  antora.yml
Labels: 4.4, don't-cherry-pick

#1222 LET and FILTER clean up
  modules/ROOT/pages/clauses/filter.adoc
  modules/ROOT/pages/clauses/let.adoc
Labels: Cypher 25

#1225 Add note clarifying Java versions for Vector index performance suggestions
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1223 Expressions / temporal operators
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/expressions/index.adoc
  modules/ROOT/pages/expressions/temporal-operators.adoc
  modules/ROOT/pages/functions/temporal/duration.adoc
  modules/ROOT/pages/functions/temporal/index.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/values-and-types/temporal.adoc
Labels: Cypher 25

#1226 CALL subqueries for cheat sheet (includes ON ERROR RETRY)
  modules/ROOT/pages/subqueries/call-subquery.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
Labels: 2025.03

#1228 2025.03 publish
  antora.yml
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/subqueries/call-subquery.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
  package-lock.json
  package.json
Labels: 2025.03

#1229 2025.04 antora update
  antora.yml
Labels: 2025.04

#1230 Uncollapse provider detail tables
  modules/ROOT/pages/genai-integrations.adoc
Labels: cherry-pick-this-to-5.x
