Repository neo4j/docs-cypher, pull requests merged in 2025-02, with the labels that each got.

#1179 bump version to 4.4.41
  antora.yml
Labels: 4.4

#1181 2025.01 publish
  antora.yml
  modules/ROOT/pages/administration/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/additional-cypher.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/appendix/gql-conformance/unsupported-mandatory.adoc
  modules/ROOT/pages/appendix/tutorials/advanced-query-tuning.adoc
  modules/ROOT/pages/appendix/tutorials/basic-query-tuning.adoc
  modules/ROOT/pages/appendix/tutorials/shortestpath-planning.adoc
  modules/ROOT/pages/clauses/call.adoc
  modules/ROOT/pages/clauses/delete.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/listing-functions.adoc
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/clauses/listing-settings.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/constraints/managing-constraints.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/graph.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/functions/user-defined.adoc
  modules/ROOT/pages/genai-integrations.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/index-hints.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/full-text-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/indexes/syntax.adoc
  modules/ROOT/pages/introduction/cypher-aura.adoc
  modules/ROOT/pages/introduction/cypher-neo4j.adoc
  modules/ROOT/pages/introduction/cypher-overview.adoc
  modules/ROOT/pages/introduction/index.adoc
  modules/ROOT/pages/patterns/reference.adoc
  modules/ROOT/pages/planning-and-tuning/execution-plans.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/planning-and-tuning/query-tuning.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/concepts.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/reference.adoc
  modules/ROOT/pages/query-caches/index.adoc
  modules/ROOT/pages/query-caches/unified-query-caches.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
  modules/ROOT/pages/syntax/naming.adoc
  modules/ROOT/pages/syntax/parameters.adoc
  modules/ROOT/pages/values-and-types/maps.adoc
  modules/ROOT/pages/values-and-types/temporal.adoc
  package-lock.json
  package.json
  preview.yml
  publish.yml
Labels: 5.x, 2025.01

#1182 Update antora for 2025.02
  antora.yml
Labels: cherry-pick-this-to-cypher-25, 2025.02

#1183 fix tables
  modules/ROOT/pages/administration/access-control/manage-roles.adoc
  modules/ROOT/pages/values-and-types/temporal.adoc
Labels: 4.4

#1184 fix tables
  modules/ROOT/pages/syntax/temporal.adoc
Labels: 4.3

#1188 Version update
  antora.yml
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/patterns/shortest-paths.adoc
Labels: Cypher 25

#1187 Remove update boundary paragraph #1186
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/clauses/with.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: Cypher 25

#1189 Add examples to temporal instant values
  modules/ROOT/pages/values-and-types/temporal.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1170 add information about new errors for revoke commands in the additions/removals section
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-operations, Cypher 25

#1192 Fixes + sign formatting in deprecations page
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1175 Conditional queries (`WHEN`)
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/conditional_query_graph.svg
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/clauses/clause-composition.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/expressions/conditional-expressions.adoc
  modules/ROOT/pages/expressions/expressions-overview.adoc
  modules/ROOT/pages/expressions/index.adoc
  modules/ROOT/pages/patterns/reference.adoc
  modules/ROOT/pages/patterns/variable-length-patterns.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/queries/composed-queries/combined-queries.adoc
  modules/ROOT/pages/queries/composed-queries/conditional-queries.adoc
  modules/ROOT/pages/queries/composed-queries/index.adoc
  modules/ROOT/pages/queries/index.adoc
  modules/ROOT/pages/subqueries/call-subquery.adoc
  modules/ROOT/pages/subqueries/collect.adoc
  modules/ROOT/pages/subqueries/count.adoc
  modules/ROOT/pages/subqueries/existential.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/syntax/parsing.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
Labels: team-cypher-surface, Cypher 25

#1193 Added note on dynamic labels in INSERT
  modules/ROOT/pages/clauses/create.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-surface, dev, cherry-pick-this-to-cypher-25

#1195 fix_antora
  publish.yml
Labels: Cypher 25

#1197 Clarify predicate function and empty list behavior
  modules/ROOT/pages/functions/predicate.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1190 Predicate expressions
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/graph_where_clause.svg
  modules/ROOT/images/path_pattern_expressions.svg
  modules/ROOT/images/predicate_operators.svg
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/expressions/conditional-expressions.adoc
  modules/ROOT/pages/expressions/expressions-overview.adoc
  modules/ROOT/pages/expressions/index.adoc
  modules/ROOT/pages/expressions/predicates/boolean-operators.adoc
  modules/ROOT/pages/expressions/predicates/comparison-operators.adoc
  modules/ROOT/pages/expressions/predicates/index.adoc
  modules/ROOT/pages/expressions/predicates/list-operators.adoc
  modules/ROOT/pages/expressions/predicates/path-pattern-expressions.adoc
  modules/ROOT/pages/expressions/predicates/string-operators.adoc
  modules/ROOT/pages/expressions/predicates/type-predicate-expressions.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/using-indexes.adoc
  modules/ROOT/pages/subqueries/existential.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/syntax/parsing.adoc
  modules/ROOT/pages/values-and-types/index.adoc
  modules/ROOT/pages/values-and-types/ordering-equality-comparison.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
  modules/ROOT/pages/values-and-types/working-with-null.adoc
Labels: Cypher 25

#1199 2025.02 publish
  antora.yml
  package-lock.json
  package.json
Labels: 5.x, 2025.02

#1200 update antora for 2025.03
  antora.yml
Labels: 2025.03

#1201 fix tables
  modules/ROOT/pages/expressions/predicates/boolean-operators.adoc
Labels: Cypher 25
