Repository neo4j/docs-cypher, pull requests merged in 2025-04, with the labels that each got.

#1231 Expressions / List expressions
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/list_expressions_graph.svg
  modules/ROOT/pages/appendix/gql-conformance/additional-cypher.adoc
  modules/ROOT/pages/expressions/index.adoc
  modules/ROOT/pages/expressions/list-expressions.adoc
  modules/ROOT/pages/functions/list.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/values-and-types/lists.adoc
Labels: Cypher 25

#1233 Small fix to keywords page for Cypher 5
  modules/ROOT/pages/syntax/keywords.adoc
Labels: cherry-pick-this-to-5.x

#1237 Update cypher replanner config settings
  modules/ROOT/pages/planning-and-tuning/query-tuning.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1236 Map expressions
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/expressions/index.adoc
  modules/ROOT/pages/expressions/map-expressions.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/values-and-types/lists.adoc
  modules/ROOT/pages/values-and-types/maps.adoc
Labels: Cypher 25

#1139 Add ALL keyword to RETURN clause as part of GQL compliance
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/clauses/return.adoc
  modules/ROOT/pages/clauses/with.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-surface, Cypher 25

#1241 Node and relationship operators
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/graph_element_operators.svg
  modules/ROOT/pages/expressions/index.adoc
  modules/ROOT/pages/expressions/node-relationship-operators.adoc
  modules/ROOT/pages/syntax/operators.adoc
Labels: Cypher 25

#1242 New WITH page for Cypher 5
  modules/ROOT/images/with_clause.svg
  modules/ROOT/pages/clauses/with.adoc
Labels: cherry-picked, cherry-pick-this-to-5.x

#1244 2025.06 release
  antora.yml
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/clauses/filter.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/let.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/return.adoc
  modules/ROOT/pages/clauses/with.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/mathematical-trigonometric.adoc
  modules/ROOT/pages/patterns/shortest-paths.adoc
  modules/ROOT/pages/queries/composed-queries/combined-queries.adoc
  modules/ROOT/pages/queries/composed-queries/conditional-queries.adoc
  modules/ROOT/pages/queries/composed-queries/index.adoc
  modules/ROOT/pages/queries/index.adoc
  modules/ROOT/pages/subqueries/call-subquery.adoc
  modules/ROOT/pages/subqueries/collect.adoc
  modules/ROOT/pages/subqueries/count.adoc
  modules/ROOT/pages/subqueries/existential.adoc
Labels: Cypher 25

#1245 Add the optional limit argument to replace()
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/string.adoc
Labels: Cypher 25

#1246 5.x temporal tags
  modules/ROOT/pages/functions/temporal/index.adoc
Labels: cherry-picked, 5.x

#1247 Cypher 25 cheat sheet tags
  modules/ROOT/pages/clauses/create.adoc
  modules/ROOT/pages/clauses/finish.adoc
  modules/ROOT/pages/clauses/foreach.adoc
  modules/ROOT/pages/clauses/limit.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/clauses/optional-match.adoc
  modules/ROOT/pages/clauses/order-by.adoc
  modules/ROOT/pages/clauses/return.adoc
  modules/ROOT/pages/clauses/skip.adoc
  modules/ROOT/pages/clauses/unwind.adoc
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/clauses/with.adoc
  modules/ROOT/pages/functions/temporal/index.adoc
  modules/ROOT/pages/patterns/fixed-length-patterns.adoc
  modules/ROOT/pages/patterns/non-linear-patterns.adoc
  modules/ROOT/pages/patterns/shortest-paths.adoc
  modules/ROOT/pages/patterns/variable-length-patterns.adoc
  modules/ROOT/pages/queries/composed-queries/combined-queries.adoc
Labels: Cypher 25

#1249 small fixes
  modules/ROOT/pages/appendix/gql-conformance/additional-cypher.adoc
  modules/ROOT/pages/clauses/remove.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/expressions/string-operators.adoc
  modules/ROOT/pages/genai-integrations.adoc
  modules/ROOT/pages/subqueries/call-subquery.adoc
Labels: Cypher 25

#1250 Update CALL import rule example
  modules/ROOT/pages/subqueries/call-subquery.adoc
Labels: cherry-pick-this-to-cypher-25, 2025.04

#1251 Expression tags
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/expressions/conditional-expressions.adoc
  modules/ROOT/pages/expressions/list-expressions.adoc
  modules/ROOT/pages/expressions/map-expressions.adoc
  modules/ROOT/pages/expressions/mathematical-operators.adoc
  modules/ROOT/pages/expressions/node-relationship-operators.adoc
  modules/ROOT/pages/expressions/predicates/boolean-operators.adoc
  modules/ROOT/pages/expressions/predicates/comparison-operators.adoc
  modules/ROOT/pages/expressions/predicates/list-operators.adoc
  modules/ROOT/pages/expressions/predicates/path-pattern-expressions.adoc
  modules/ROOT/pages/expressions/predicates/string-operators.adoc
  modules/ROOT/pages/expressions/predicates/type-predicate-expressions.adoc
  modules/ROOT/pages/expressions/string-operators.adoc
  modules/ROOT/pages/expressions/temporal-operators.adoc
  modules/ROOT/pages/queries/combined-queries.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1253 Expressions tags for 25
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/expressions/conditional-expressions.adoc
  modules/ROOT/pages/expressions/list-expressions.adoc
  modules/ROOT/pages/expressions/map-expressions.adoc
  modules/ROOT/pages/expressions/mathematical-operators.adoc
  modules/ROOT/pages/expressions/node-relationship-operators.adoc
  modules/ROOT/pages/expressions/predicates/boolean-operators.adoc
  modules/ROOT/pages/expressions/predicates/comparison-operators.adoc
  modules/ROOT/pages/expressions/predicates/list-operators.adoc
  modules/ROOT/pages/expressions/predicates/path-pattern-expressions.adoc
  modules/ROOT/pages/expressions/predicates/string-operators.adoc
  modules/ROOT/pages/expressions/predicates/type-predicate-expressions.adoc
  modules/ROOT/pages/expressions/string-operators.adoc
  modules/ROOT/pages/expressions/temporal-operators.adoc
  modules/ROOT/pages/queries/composed-queries/combined-queries.adoc
Labels: cherry-picked, Cypher 25

#1255 Add timestamp() to functions overview page
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/functions/temporal/index.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1256 4.4 timestamp
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/scalar.adoc
Labels: 4.4, cherry-picked

#1254 Page aliases for 25
  modules/ROOT/pages/expressions/conditional-expressions.adoc
  modules/ROOT/pages/expressions/index.adoc
  modules/ROOT/pages/expressions/predicates/type-predicate-expressions.adoc
  modules/ROOT/pages/queries/composed-queries/combined-queries.adoc
Labels: Cypher 25

#1258 aliases
  modules/ROOT/pages/queries/combined-queries.adoc
Labels: cherry-pick-this-to-5.x

#1239 Added relationship PBAC to the Deprecations, additions, and compatibility page
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: team-cypher-operations, cherry-pick-this-to-cypher-25, 2025.04

#1260 Tags for Cypher 25 cheat sheet
  modules/ROOT/pages/clauses/filter.adoc
  modules/ROOT/pages/clauses/let.adoc
  modules/ROOT/pages/functions/mathematical-trigonometric.adoc
  modules/ROOT/pages/functions/temporal/index.adoc
  modules/ROOT/pages/queries/composed-queries/combined-queries.adoc
  modules/ROOT/pages/queries/composed-queries/conditional-queries.adoc
Labels: Cypher 25

#1261 fix variable names
  modules/ROOT/pages/clauses/with.adoc
Labels: cherry-pick-this-to-5.x

#1263 Publish 2025.04
  antora.yml
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/subqueries/call-subquery.adoc
Labels: 5.x, 2025.04

#1264 Bump the version number to 2025.05
  antora.yml
Labels: 2025.05
