Repository neo4j/docs-cypher, pull requests merged in 2025-05, with the labels that each got.

#1267 Fix broken link in WITH clause chapter
  modules/ROOT/pages/clauses/with.adoc
Labels: cherry-pick-this-to-5.x, dev, cherry-pick-this-to-cypher-25

#1266 Remove unsupported versions from Additions & Deprecations page
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1265 Fix links
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/clauses/call.adoc
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/user-defined.adoc
  modules/ROOT/pages/genai-integrations.adoc
  modules/ROOT/pages/indexes/semantic-indexes/full-text-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/introduction/cypher-neo4j.adoc
  modules/ROOT/pages/patterns/reference.adoc
  modules/ROOT/pages/planning-and-tuning/operators/operators-detail.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/concepts.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/reference.adoc
  modules/ROOT/pages/syntax/parameters.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1269 Fix broken links and clean up
  modules/ROOT/pages/administration/access-control/built-in-roles.adoc
  modules/ROOT/pages/clauses/call.adoc
  modules/ROOT/pages/clauses/load-csv.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/user-defined.adoc
  modules/ROOT/pages/indexes-for-full-text-search.adoc
  modules/ROOT/pages/introduction/cypher-aura.adoc
  modules/ROOT/pages/introduction/cypher-neo4j.adoc
  modules/ROOT/pages/introduction/cypher-tutorial.adoc
  modules/ROOT/pages/introduction/neo4j-databases-graphs.adoc
  modules/ROOT/pages/introduction/quering-updating-administering.adoc
  modules/ROOT/pages/introduction/transactions.adoc
  modules/ROOT/pages/introduction/uniqueness.adoc
  modules/ROOT/pages/syntax/operators.adoc
  modules/ROOT/pages/values-and-types/spatial.adoc
Labels: 4.4

#1270 Standardise null, true, false formatting
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/clauses/with.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/expressions/list-expressions.adoc
  modules/ROOT/pages/expressions/map-expressions.adoc
  modules/ROOT/pages/expressions/node-relationship-operators.adoc
  modules/ROOT/pages/expressions/predicates/boolean-operators.adoc
  modules/ROOT/pages/expressions/predicates/index.adoc
  modules/ROOT/pages/expressions/predicates/list-operators.adoc
  modules/ROOT/pages/expressions/predicates/path-pattern-expressions.adoc
  modules/ROOT/pages/expressions/predicates/string-operators.adoc
  modules/ROOT/pages/expressions/predicates/type-predicate-expressions.adoc
  modules/ROOT/pages/expressions/string-operators.adoc
  modules/ROOT/pages/functions/predicate.adoc
  modules/ROOT/pages/functions/scalar.adoc
  modules/ROOT/pages/functions/vector.adoc
  modules/ROOT/pages/subqueries/call-subquery.adoc
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
  modules/ROOT/pages/syntax/keywords.adoc
  modules/ROOT/pages/values-and-types/ordering-equality-comparison.adoc
  modules/ROOT/pages/values-and-types/property-structural-constructed.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1271 Fix WITH graph
  modules/ROOT/images/with_clause.svg
Labels: cherry-pick-this-to-5.x, cherry-pick-this-to-cypher-25

#1276 Clarify removal of update boundary
  modules/ROOT/pages/clauses/clause-composition.adoc
  modules/ROOT/pages/clauses/with.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: Cypher 25

#1277 Update the version number to 4.4.43
  antora.yml
Labels: 4.4, don't-cherry-pick

#1073 auto-cherry-pick for docs-cypher
  .backportrc.json
  .github/workflows/auto-backport.yml
  README.adoc
Labels: auto-cherry-pick, auto-cherry-pick-to-5.x, auto-cherry-pick-to-cypher-25

#1278 test auto cherry-pick
  README.adoc
Labels: cherry-pick, cherry-pick-to-5.x, cherry-pick-to-cypher-25

#1274 Order by improvement
  modules/ROOT/images/graph_order_by_clause.svg
  modules/ROOT/pages/clauses/order-by.adoc
Labels: cherry-pick-this-to-5.x, cherry-pick-to-cypher-25

#1282 Order by improvement (#1274)
  modules/ROOT/images/graph_order_by_clause.svg
  modules/ROOT/pages/clauses/order-by.adoc
Labels: cherry-picked, Cypher 25

#1286 Fix example in core concepts page
  modules/ROOT/pages/queries/concepts.adoc
Labels: cherry-pick-to-5.x, cherry-pick-to-cypher-25

#1287 Uncollapse limitations and known issues in vector indexes
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
Labels: cherry-pick-this-to-5.x

#1291 Fix broken anchors
  modules/ROOT/pages/clauses/call-subquery.adoc
  modules/ROOT/pages/clauses/delete.adoc
  modules/ROOT/pages/clauses/order-by.adoc
  modules/ROOT/pages/clauses/transaction-clauses.adoc
  modules/ROOT/pages/execution-plans/operators.adoc
  modules/ROOT/pages/introduction/cypher-neo4j.adoc
  modules/ROOT/pages/introduction/cypher-overview.adoc
  modules/ROOT/pages/query-tuning/query-options.adoc
  modules/ROOT/pages/syntax/parameters.adoc
  modules/ROOT/pages/values-and-types/maps.adoc
  modules/ROOT/pages/values-and-types/property-structural-composite.adoc
  modules/ROOT/pages/values-and-types/spatial.adoc
Labels: 4.4

#1292 Fix broken anchors (#1290)
  modules/ROOT/pages/appendix/gql-conformance/additional-cypher.adoc
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/clauses/clause-composition.adoc
  modules/ROOT/pages/clauses/index.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/constraints/syntax.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/expressions/map-expressions.adoc
  modules/ROOT/pages/expressions/string-operators.adoc
  modules/ROOT/pages/functions/index.adoc
  modules/ROOT/pages/functions/list.adoc
  modules/ROOT/pages/functions/string.adoc
  modules/ROOT/pages/functions/vector.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/syntax.adoc
  modules/ROOT/pages/patterns/non-linear-patterns.adoc
  modules/ROOT/pages/planning-and-tuning/execution-plans.adoc
  modules/ROOT/pages/planning-and-tuning/operators/index.adoc
  modules/ROOT/pages/subqueries/collect.adoc
  modules/ROOT/pages/subqueries/count.adoc
  modules/ROOT/pages/subqueries/existential.adoc
  modules/ROOT/pages/syntax/parameters.adoc
  modules/ROOT/pages/values-and-types/ordering-equality-comparison.adoc
  modules/ROOT/pages/values-and-types/spatial.adoc
Labels: cherry-picked, Cypher 25
