Repository neo4j/docs-cypher, pull requests merged in 2025-06, with the labels that each got.

#1293 Cypher 25 query fixes
  modules/ROOT/pages/clauses/filter.adoc
  modules/ROOT/pages/clauses/let.adoc
  modules/ROOT/pages/clauses/merge.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/expressions/map-expressions.adoc
  modules/ROOT/pages/functions/mathematical-trigonometric.adoc
Labels: Cypher 25

#1294 2025.06 changes to mandatory GQL features
  modules/ROOT/pages/appendix/gql-conformance/index.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-mandatory.adoc
  modules/ROOT/pages/appendix/gql-conformance/unsupported-mandatory.adoc
Labels: cherry-pick-to-cypher-25, 2025.06

#1298 Fixing problem with label
  modules/ROOT/pages/planning-and-tuning/runtimes/concepts.adoc
Labels: bug

#1273 NEXT documentation
  modules/ROOT/content-nav.adoc
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/queries/composed-queries/index.adoc
  modules/ROOT/pages/queries/composed-queries/sequential-queries.adoc
  modules/ROOT/pages/queries/index.adoc
  modules/ROOT/pages/syntax/keywords.adoc
  package-lock.json
Labels: team-cypher-surface

#1301 Add best practice example to subqueries in transactions with deadlocks section
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
Labels: cherry-pick-this-to-5.x, team-cypher-runtime, dev, cherry-pick-to-cypher-25

#1300 Correct note about supported runtime for transaction subqueries
  modules/ROOT/pages/subqueries/subqueries-in-transactions.adoc
Labels: team-cypher-runtime, cherry-pick-to-cypher-25, 2025.06

#1304 Remove option to create indexes/constraints with index provider
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/indexes/search-performance-indexes/managing-indexes.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
Labels: Cypher 25

#1306 Forgotten images
  modules/ROOT/images/filter-clause.svg
  modules/ROOT/images/filter_clause.svg
  modules/ROOT/images/graph-order-by-clause.svg
  modules/ROOT/images/graph-with-clause.svg
  modules/ROOT/images/let-graph.svg
  modules/ROOT/images/let_clause.svg
  modules/ROOT/images/order-by-graph.svg
  modules/ROOT/images/sequential-queries-graph.svg
  modules/ROOT/images/with-graph.svg
  modules/ROOT/images/with_clause.svg
  modules/ROOT/pages/clauses/filter.adoc
  modules/ROOT/pages/clauses/let.adoc
  modules/ROOT/pages/clauses/order-by.adoc
  modules/ROOT/pages/clauses/where.adoc
  modules/ROOT/pages/clauses/with.adoc
  modules/ROOT/pages/queries/composed-queries/sequential-queries.adoc
Labels: Cypher 25

#1308 Add removed procedures to removed in Cypher 25 list
  modules/ROOT/pages/clauses/listing-procedures.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/indexes/semantic-indexes/vector-indexes.adoc
  modules/ROOT/pages/planning-and-tuning/runtimes/reference.adoc
Labels: Cypher 25

#1303 Match modes (`DIFFERENT RELATIONSHIPS` + `REPEATABLE ELEMENTS`)
  modules/ROOT/content-nav.adoc
  modules/ROOT/images/different-relationships-graph.svg
  modules/ROOT/images/match-modes-graph.svg
  modules/ROOT/images/match-modes-reference.svg
  modules/ROOT/images/repeatable-elements-graph.svg
  modules/ROOT/pages/appendix/gql-conformance/supported-optional.adoc
  modules/ROOT/pages/clauses/match.adoc
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
  modules/ROOT/pages/patterns/index.adoc
  modules/ROOT/pages/patterns/match-modes.adoc
  modules/ROOT/pages/patterns/non-linear-patterns.adoc
  modules/ROOT/pages/patterns/reference.adoc
Labels: Cypher 25

#1309 fix Cypher 25 queries
  modules/ROOT/images/repeatable-elements-graph.svg
  modules/ROOT/pages/clauses/use.adoc
  modules/ROOT/pages/patterns/match-modes.adoc
  modules/ROOT/pages/queries/composed-queries/sequential-queries.adoc
Labels: Cypher 25, cherry-pick-this-to-cypher-25

#1311 add xrefs for constraints index page
  modules/ROOT/pages/constraints/index.adoc
Labels: cherry-pick-to-cypher-25, cherry-pick-to-cypher-5

#1310 match modes and NEXT cheat sheet tags
  modules/ROOT/pages/patterns/match-modes.adoc
  modules/ROOT/pages/queries/composed-queries/sequential-queries.adoc
Labels: Cypher 25, cherry-pick-to-cypher-25

#1316 Mark 25 as prerelease - force sitemap to Cypher 5
  antora.yml
Labels: cherry-pick-to-cypher-25

#1320 introduction note about Cypher 25
  modules/ROOT/pages/introduction/index.adoc
Labels: cherry-pick-to-cypher-25

#1324 add cypher-5 to pr checks
  .github/workflows/docs-pr-checks.yml
  .github/workflows/docs-teardown.yml
Labels: cherry-pick-to-cypher-25, cherry-pick-to-cypher-5

#1314 Add language version control commands to Additions page
  modules/ROOT/pages/deprecations-additions-removals-compatibility.adoc
Labels: cherry-pick-to-cypher-25, cherry-pick-to-cypher-5
